export interface CambridgeWritingTask {
    book: number;
    test: number;
    task: 1 | 2;
    type: string;
    prompt: string;
}

export const CAMBRIDGE_WRITING_TASKS: CambridgeWritingTask[] = [
    // ─── Cambridge 9 ──────────────────────────────────────────────────────────
    { book: 9, test: 1, task: 1, type: 'Bar chart', prompt: 'The bar chart below shows the percentage of people in different age groups who used the internet every day in the UK in 2012. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 9, test: 1, task: 2, type: 'Opinion essay', prompt: 'Some people say that advertising is extremely successful at persuading us to buy things. Other people think that advertising is so common that we no longer pay attention to it. Discuss both views and give your own opinion.' },
    { book: 9, test: 2, task: 1, type: 'Table', prompt: 'The table below shows the proportion of different categories of families living in poverty in Australia in 1999. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 9, test: 2, task: 2, type: 'Discussion essay', prompt: 'The best way to reduce the number of traffic accidents is to raise the age at which young people are allowed to drive cars or motorbikes. To what extent do you agree or disagree?' },
    { book: 9, test: 3, task: 1, type: 'Line graph', prompt: 'The graph below shows the average number of UK cinema admissions per person from 1990 to 2010. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 9, test: 3, task: 2, type: 'Discussion essay', prompt: 'Some people think that all university students should study whatever they like. Others believe that they should only be allowed to study subjects that will be useful in the future, such as those related to science and technology. Discuss both views and give your own opinion.' },
    { book: 9, test: 4, task: 1, type: 'Bar chart', prompt: 'The bar chart below shows the number of overseas students enrolled in three universities in the UK in 2004. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 9, test: 4, task: 2, type: 'Discussion essay', prompt: 'Some people think that it is important to use leisure time for activities that develop the mind, such as reading and doing word puzzles. Other people feel that it is important to give your mind a rest during leisure time. Discuss both views and give your own opinion.' },

    // ─── Cambridge 10 ─────────────────────────────────────────────────────────
    { book: 10, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows the amount of money per week spent on fast food in Britain. The graph shows the trends in consumption of fast foods. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 10, test: 1, task: 2, type: 'Opinion essay', prompt: 'Some people think that a sense of competition in children should be encouraged. Others believe that children who are taught to co-operate rather than compete become more useful adults. Discuss both views and give your own opinion.' },
    { book: 10, test: 2, task: 1, type: 'Maps', prompt: 'The maps below show the centre of a small town called Islip as it is now, and plans for its development. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 10, test: 2, task: 2, type: 'Opinion essay', prompt: 'Some people believe that unpaid community service should be a compulsory part of high school programmes (for example working for a charity, improving the neighbourhood or teaching sports to younger children). To what extent do you agree or disagree?' },
    { book: 10, test: 3, task: 1, type: 'Line graph', prompt: 'The graph below shows the unemployment rate and the number of people who left school at 16 in a European country from 1985 to 1995. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 10, test: 3, task: 2, type: 'Discussion essay', prompt: 'News editors decide what to broadcast on television and what to print in newspapers. What factors do you think influence these decisions? Do we become used to bad news, and does this have a negative effect on society?' },
    { book: 10, test: 4, task: 1, type: 'Pie charts', prompt: 'The pie charts below show the percentage of household electricity used for various purposes in two countries. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 10, test: 4, task: 2, type: 'Opinion essay', prompt: 'Although countries with long average working hours are economically successful, this may have some negative effects on society. To what extent do you agree or disagree with this view?' },

    // ─── Cambridge 11 ─────────────────────────────────────────────────────────
    { book: 11, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows how much time UK teenagers (11–17 years old) spent online in 2009, and what they used the internet for. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 11, test: 1, task: 2, type: 'Opinion essay', prompt: 'More and more people are becoming seriously overweight. Some people think a solution to this problem is to increase the price of fattening foods. To what extent do you agree or disagree with this opinion?' },
    { book: 11, test: 2, task: 1, type: 'Table', prompt: 'The table below gives information on consumer spending on different items in five different countries in 2002. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 11, test: 2, task: 2, type: 'Discussion essay', prompt: 'Governments should spend more money on railways than on building new roads. To what extent do you agree or disagree with this statement?' },
    { book: 11, test: 3, task: 1, type: 'Diagram', prompt: 'The diagrams below show how the building at 14 Trinity Avenue has changed over two periods. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 11, test: 3, task: 2, type: 'Discussion essay', prompt: 'Today, the high sales of popular consumer goods reflect the power of advertising and not the real needs of the society in which they are sold. To what extent do you agree or disagree?' },
    { book: 11, test: 4, task: 1, type: 'Pie charts', prompt: 'The pie charts below show the changes in how people in an urban area in New Zealand spent their leisure time, in 1991 and 2011. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 11, test: 4, task: 2, type: 'Discussion essay', prompt: 'Many museums and historical sites are mainly visited by tourists, not local people. Why is this the case and what can be done to attract more local people to visit these places?' },

    // ─── Cambridge 12 ─────────────────────────────────────────────────────────
    { book: 12, test: 1, task: 1, type: 'Pie charts', prompt: 'The charts below show the proportions of British students at one university in England who were able to speak other languages in addition to English, in 2000 and 2010. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 12, test: 1, task: 2, type: 'Opinion essay', prompt: 'In some countries, some people think it is necessary to spend large sums of money on constructing new railway lines for very fast trains between cities. Others believe the money should be spent on improving existing public transport. Discuss both views and give your own opinion.' },
    { book: 12, test: 2, task: 1, type: 'Line graph', prompt: 'The graph below shows average carbon dioxide (CO2) emissions per person in the UK, Sweden, Italy and Portugal between 1967 and 2007. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 12, test: 2, task: 2, type: 'Opinion essay', prompt: 'Some people think that governments should ban dangerous sports, while others think people should have freedom to do any sport or activity. Discuss both views and give your own opinion.' },
    { book: 12, test: 3, task: 1, type: 'Bar charts', prompt: 'The charts below show the percentage of water used for different purposes in six areas of the world. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 12, test: 3, task: 2, type: 'Discussion essay', prompt: 'Some people believe that it is best to accept a bad situation, such as an unsatisfactory job or shortage of money. Others argue that it is better to try to improve such situations. Discuss both views and give your own opinion.' },
    { book: 12, test: 4, task: 1, type: 'Bar chart', prompt: 'The bar chart below shows the number of people who visited three kinds of tourist attraction in the UK between 1999 and 2009. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 12, test: 4, task: 2, type: 'Opinion essay', prompt: 'Many parents today organise extra lessons for their children in subjects they find difficult or help with school work at home. Is this a positive or negative development?' },

    // ─── Cambridge 13 ─────────────────────────────────────────────────────────
    { book: 13, test: 1, task: 1, type: 'Pie charts', prompt: 'The charts below show the percentages of men and women in employment in three countries in 2005 and 2015. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 13, test: 1, task: 2, type: 'Opinion essay', prompt: 'Some people say that music is a good way of bringing people of different cultures and ages together. To what extent do you agree or disagree with this opinion?' },
    { book: 13, test: 2, task: 1, type: 'Table', prompt: 'The table below shows how adults in Australia spent their time each week in 1999 and 2015. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 13, test: 2, task: 2, type: 'Opinion essay', prompt: 'Some people think that all teenagers should be required to do unpaid work in their local community. Others believe young people should be free to choose what to do with their spare time. Discuss both views and give your opinion.' },
    { book: 13, test: 3, task: 1, type: 'Line graph', prompt: 'The graph below shows the average monthly change in the prices of three metals during 2014. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 13, test: 3, task: 2, type: 'Opinion essay', prompt: 'In the future, nobody will buy printed newspapers or books because they will be able to read everything they want online without paying. To what extent do you agree or disagree with this statement?' },
    { book: 13, test: 4, task: 1, type: 'Bar chart', prompt: 'The chart below shows information about changes in average house prices in five different cities between 1990 and 2002 compared with the average house prices in 1989. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 13, test: 4, task: 2, type: 'Opinion essay', prompt: 'Some people feel that entertainers (e.g. film stars, pop musicians or sports stars) are paid too much money. Do you agree or disagree? Which other types of jobs should be highly paid?' },

    // ─── Cambridge 14 ─────────────────────────────────────────────────────────
    { book: 14, test: 1, task: 1, type: 'Maps', prompt: 'The maps below show a village called Stokeford in 1930 and 2010. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 14, test: 1, task: 2, type: 'Opinion essay', prompt: 'Some people believe that it is good to share as much information as possible in scientific research, business and the academic world. Others believe that some information is too important or too valuable to be shared freely. Discuss both views and give your own opinion.' },
    { book: 14, test: 2, task: 1, type: 'Bar charts', prompt: 'The charts below give information about USA marriage and divorce rates between 1970 and 2000, and the marital status of adult Americans in two of those years. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 14, test: 2, task: 2, type: 'Opinion essay', prompt: 'The 21st century has begun. What changes do you think this new century will bring? Use your own ideas, knowledge and experience and support your arguments with examples and relevant evidence.' },
    { book: 14, test: 3, task: 1, type: 'Diagram', prompt: 'The diagram below shows how a central heating system in a house works. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 14, test: 3, task: 2, type: 'Opinion essay', prompt: 'Some people say that the only reason for learning a foreign language is in order to travel to or work in a foreign country. Others say that these are not the only reasons why someone should learn a foreign language. Discuss both these views and give your own opinion.' },
    { book: 14, test: 4, task: 1, type: 'Table', prompt: 'The table below gives information about the underground railway systems in six cities. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 14, test: 4, task: 2, type: 'Opinion essay', prompt: 'Every year several languages die out. Some people think that this is not important because life will be easier if there are fewer languages in the world. To what extent do you agree or disagree with this opinion?' },

    // ─── Cambridge 15 ─────────────────────────────────────────────────────────
    { book: 15, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows the percentage of households in owned and rented accommodation in England and Wales between 1918 and 2011. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 15, test: 1, task: 2, type: 'Opinion essay', prompt: 'Some people say that the main environmental problem of our time is the loss of particular species of plants and animals. Others say that there are more important environmental problems. Discuss both views and give your own opinion.' },
    { book: 15, test: 2, task: 1, type: 'Pie charts', prompt: 'The charts below show the percentage of water used for different purposes in six areas of the world. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 15, test: 2, task: 2, type: 'Opinion essay', prompt: 'Some people think that strict punishments for driving offences are the key to reducing traffic accidents. Others, however, believe that other measures would be more effective in improving road safety. Discuss both views and give your own opinion.' },
    { book: 15, test: 3, task: 1, type: 'Line graphs', prompt: 'The graph below shows the quantities of goods transported in the UK between 1974 and 2002 by four different modes of transport. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 15, test: 3, task: 2, type: 'Opinion essay', prompt: 'Some people say that now we can see films on our phones or tablets there is no need to go to the cinema. Others say that the cinema is still relevant. Discuss both views and give your own opinion.' },
    { book: 15, test: 4, task: 1, type: 'Bar chart', prompt: 'The chart below shows information about the age groups of people in employment in four different countries. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 15, test: 4, task: 2, type: 'Opinion essay', prompt: 'In some countries, owning a home rather than renting one is very important for people. Why might this be the case? Do you think this is a positive or negative situation?' },

    // ─── Cambridge 16 ─────────────────────────────────────────────────────────
    { book: 16, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows the percentage of households in owned and rented accommodation in three cities in 2015. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 16, test: 1, task: 2, type: 'Opinion essay', prompt: 'In some countries, people spend long hours at work. Why does this happen? Is it a positive or negative development?' },
    { book: 16, test: 2, task: 1, type: 'Maps', prompt: 'The maps below show changes in the town of Harborne from 2010 to the present day. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 16, test: 2, task: 2, type: 'Discussion essay', prompt: 'Some people think that the government should pay for healthcare and education, but others believe it is not the government\'s responsibility. Discuss both views and give your own opinion.' },
    { book: 16, test: 3, task: 1, type: 'Pie charts', prompt: 'The pie charts below show the percentage of food imported to the UK from five areas of the world in 2009 and 2019. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 16, test: 3, task: 2, type: 'Opinion essay', prompt: 'Some people believe that nowadays we have too many choices. To what extent do you agree or disagree with this statement?' },
    { book: 16, test: 4, task: 1, type: 'Line graph', prompt: 'The graph below shows the number of tourists visiting a particular Caribbean island between 2010 and 2017. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 16, test: 4, task: 2, type: 'Opinion essay', prompt: 'Some people think that success in life comes from taking risks or chances. Others believe that success results from careful planning. Discuss both views and give your own opinion.' },

    // ─── Cambridge 17 ─────────────────────────────────────────────────────────
    { book: 17, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows the percentage of people who ate five portions of fruit and/or vegetables per day in the UK between 2001 and 2008. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 17, test: 1, task: 2, type: 'Opinion essay', prompt: 'The most important thing about being rich is it gives a person the opportunity to help others. Do you agree or disagree?' },
    { book: 17, test: 2, task: 1, type: 'Table', prompt: 'The table below shows the sales made by a coffee shop in an office building on a typical weekday. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 17, test: 2, task: 2, type: 'Discussion essay', prompt: 'Some people say that to be a good teacher you must have personal qualities such as warmth and sympathy, whereas others think that subject knowledge is all that matters. Discuss both views and give your own opinion.' },
    { book: 17, test: 3, task: 1, type: 'Line graph + table', prompt: 'The graph and table below give information about water use worldwide and water consumption in two different countries. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 17, test: 3, task: 2, type: 'Opinion essay', prompt: 'It is generally accepted that exercise is good for children and teenagers. Therefore, physical education and sport should be compulsory for all students in schools. To what extent do you agree or disagree?' },
    { book: 17, test: 4, task: 1, type: 'Bar chart', prompt: 'The bar chart below shows the percentage of students in four different year groups who said they sometimes or often used the internet for school work. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 17, test: 4, task: 2, type: 'Opinion essay', prompt: 'Some people think that schools should select their students according to their academic abilities, while others believe that it is better to have students of all abilities in the same school. Discuss both views and give your own opinion.' },

    // ─── Cambridge 18 ─────────────────────────────────────────────────────────
    { book: 18, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows the percentage of time spent on homework by students in three countries in 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 18, test: 1, task: 2, type: 'Opinion essay', prompt: 'Some people think that the range of technology available to individuals today is increasing the gap between rich and poor people, while others think it is having the opposite effect. Discuss both views and give your own opinion.' },
    { book: 18, test: 2, task: 1, type: 'Pie charts', prompt: 'The charts below show the percentage of young people engaged in various activities in 2000 and 2015. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 18, test: 2, task: 2, type: 'Opinion essay', prompt: 'Governments should not have to provide care or financial support for elderly people because it is the responsibility of each person to prepare for retirement. To what extent do you agree or disagree?' },
    { book: 18, test: 3, task: 1, type: 'Maps', prompt: 'The maps below show how transport links in a city changed between 1990 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 18, test: 3, task: 2, type: 'Discussion essay', prompt: 'Some people believe children should be allowed to stay at home and play until they are six or seven years old before starting school. Others think it is important for young children to go to school as soon as possible. Discuss both views and give your own opinion.' },
    { book: 18, test: 4, task: 1, type: 'Line graph', prompt: 'The graph below shows the percentage of households in one country that had various facilities and amenities between 1970 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 18, test: 4, task: 2, type: 'Opinion essay', prompt: 'Some people say that the purpose of education is to prepare individuals to be useful to society, whereas others say education is mainly about personal development. Discuss both views and give your own opinion.' },

    // ─── Cambridge 19 ─────────────────────────────────────────────────────────
    { book: 19, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows how much money people in a European country spend on various categories of goods and services. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 19, test: 1, task: 2, type: 'Opinion essay', prompt: 'In many countries, there is a shortage of housing in big cities. What do you think are the main causes of this problem? What are the possible solutions?' },
    { book: 19, test: 2, task: 1, type: 'Pie charts', prompt: 'The charts below show information about travel to and from the UK in 2009 and 2019. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 19, test: 2, task: 2, type: 'Discussion essay', prompt: 'Some people say that when older people retire, they should be replaced by younger people who have more up-to-date knowledge of the world. Other people think it is better to keep older workers in employment. Discuss both views and give your own opinion.' },
    { book: 19, test: 3, task: 1, type: 'Line graph', prompt: 'The graph below shows how the amount spent on fast food changed in four European countries between 1970 and 1990. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 19, test: 3, task: 2, type: 'Opinion essay', prompt: 'Some people think that technology, such as smartphones, has made our lives too complicated. Others disagree. Discuss both views and give your own opinion.' },
    { book: 19, test: 4, task: 1, type: 'Bar chart', prompt: 'The chart below shows the percentage of adults in the USA who ate out at least once a week in 2003, 2009 and 2015. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 19, test: 4, task: 2, type: 'Opinion essay', prompt: 'Some people believe that allowing children to make their own choices on everyday matters (such as food, clothes and entertainment) is likely to result in a society of individuals who only think about their own wishes. Other people believe it is important for children to make decisions about things that affect them. Discuss both views and give your own opinion.' },

    // ─── Cambridge 20 ─────────────────────────────────────────────────────────
    { book: 20, test: 1, task: 1, type: 'Bar chart', prompt: 'The chart below shows the percentage of males and females in further education in one country between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 20, test: 1, task: 2, type: 'Opinion essay', prompt: 'In some societies, more and more people choose to live on their own. What are the reasons for this? Is this a positive or negative development for society?' },
    { book: 20, test: 2, task: 1, type: 'Table', prompt: 'The table below shows information about the population and number of vehicles in five regions. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 20, test: 2, task: 2, type: 'Discussion essay', prompt: 'Some people think that the best way to improve road safety is to increase the minimum driving age. Others think there are better ways to achieve this. Discuss both views and give your own opinion.' },
    { book: 20, test: 3, task: 1, type: 'Maps', prompt: 'The maps below show how a seaside town changed between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 20, test: 3, task: 2, type: 'Opinion essay', prompt: 'Some people believe that studying at university or college is the best route to a successful career, while others believe that it is better to get a job straight after school. Discuss both views and give your own opinion.' },
    { book: 20, test: 4, task: 1, type: 'Line graph', prompt: 'The graph below shows the percentage of the population in one country who owned at least one car between 1950 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.' },
    { book: 20, test: 4, task: 2, type: 'Opinion essay', prompt: 'Some people believe that the best way to improve public health is by increasing the number of sports facilities. Others, however, think this would have little effect on public health and that other measures are required. Discuss both views and give your own opinion.' },
];

export function getCambridgeWritingTasks(book: number, test: number): CambridgeWritingTask[] {
    return CAMBRIDGE_WRITING_TASKS.filter(t => t.book === book && t.test === test);
}

export const CAMBRIDGE_WRITING_BOOKS = [...new Set(CAMBRIDGE_WRITING_TASKS.map(t => t.book))].sort((a, b) => a - b);
