import type { SynonymGroup } from './paraphraseData';

export const EXPANDED_SYNONYM_GROUPS: SynonymGroup[] = [
  {
    category: 'Academic Writing Connectors',
    icon: '🔗',
    pairs: [
      { base: 'therefore', synonyms: ['consequently', 'thus', 'hence', 'as a result', 'for this reason', 'accordingly', 'so'] },
      { base: 'however', synonyms: ['nevertheless', 'nonetheless', 'yet', 'still', 'even so', 'that said', 'on the other hand'] },
      { base: 'furthermore', synonyms: ['moreover', 'additionally', 'in addition', 'besides', 'also', 'what is more', 'on top of this'] },
      { base: 'although', synonyms: ['though', 'even though', 'while', 'whilst', 'despite the fact that', 'notwithstanding', 'in spite of the fact that'] },
      { base: 'for example', synonyms: ['for instance', 'such as', 'namely', 'to illustrate', 'in particular', 'as an example', 'to give an example'] },
      { base: 'in conclusion', synonyms: ['to conclude', 'to summarise', 'in summary', 'overall', 'ultimately', 'to sum up', 'in brief'] },
      { base: 'in contrast', synonyms: ['on the contrary', 'conversely', 'by contrast', 'on the other hand', 'whereas', 'while', 'alternatively'] },
    ],
  },
  {
    category: 'তুলনা / Comparing & Contrasting',
    icon: '⚖️',
    pairs: [
      { base: 'similar', synonyms: ['alike', 'comparable', 'analogous', 'equivalent', 'parallel', 'corresponding', 'related'] },
      { base: 'different', synonyms: ['distinct', 'dissimilar', 'divergent', 'contrasting', 'varying', 'unlike', 'disparate'] },
      { base: 'compare', synonyms: ['contrast', 'juxtapose', 'measure against', 'evaluate alongside', 'examine in relation to', 'assess comparatively'] },
      { base: 'whereas', synonyms: ['while', 'on the other hand', 'in contrast', 'conversely', 'by comparison', 'alternatively', 'though'] },
      { base: 'likewise', synonyms: ['similarly', 'in the same way', 'equally', 'correspondingly', 'in like manner', 'by the same token'] },
      { base: 'despite', synonyms: ['notwithstanding', 'in spite of', 'regardless of', 'irrespective of', 'even with', 'although'] },
    ],
  },
  {
    category: 'মতামত / Agreement & Disagreement',
    icon: '🤝',
    pairs: [
      { base: 'agree', synonyms: ['concur', 'consensus', 'accord', 'support', 'endorse', 'subscribe to', 'align with'] },
      { base: 'disagree', synonyms: ['dispute', 'oppose', 'contest', 'challenge', 'refute', 'reject', 'contradict'] },
      { base: 'argue', synonyms: ['contend', 'maintain', 'assert', 'claim', 'posit', 'propose', 'advocate'] },
      { base: 'oppose', synonyms: ['resist', 'object to', 'counter', 'dispute', 'rebut', 'challenge', 'contradict'] },
      { base: 'accept', synonyms: ['acknowledge', 'recognise', 'admit', 'concede', 'grant', 'affirm', 'validate'] },
      { base: 'doubt', synonyms: ['question', 'challenge', 'dispute', 'scepticism', 'uncertainty', 'hesitation', 'reservation'] },
    ],
  },
  {
    category: 'গবেষণা / Research & Study',
    icon: '🔬',
    pairs: [
      { base: 'study', synonyms: ['research', 'investigation', 'analysis', 'examination', 'inquiry', 'survey', 'review'] },
      { base: 'find / conclude', synonyms: ['determine', 'establish', 'identify', 'reveal', 'demonstrate', 'indicate', 'suggest'] },
      { base: 'data', synonyms: ['evidence', 'findings', 'results', 'statistics', 'figures', 'information', 'records'] },
      { base: 'method', synonyms: ['approach', 'technique', 'procedure', 'strategy', 'process', 'means', 'framework'] },
      { base: 'result', synonyms: ['outcome', 'finding', 'conclusion', 'consequence', 'effect', 'impact', 'product'] },
      { base: 'prove', synonyms: ['demonstrate', 'confirm', 'establish', 'verify', 'validate', 'corroborate', 'substantiate'] },
      { base: 'analyse', synonyms: ['examine', 'investigate', 'evaluate', 'assess', 'scrutinise', 'explore', 'interpret'] },
    ],
  },
  {
    category: 'সময় / Time & Duration',
    icon: '⏱️',
    pairs: [
      { base: 'recently', synonyms: ['lately', 'in recent years', 'of late', 'in the past few years', 'nowadays', 'currently', 'presently'] },
      { base: 'gradually', synonyms: ['progressively', 'incrementally', 'steadily', 'slowly', 'step by step', 'bit by bit', 'over time'] },
      { base: 'immediately', synonyms: ['instantly', 'promptly', 'at once', 'straightaway', 'without delay', 'swiftly', 'directly'] },
      { base: 'eventually', synonyms: ['ultimately', 'in due course', 'in time', 'finally', 'at last', 'sooner or later', 'in the long run'] },
      { base: 'previously', synonyms: ['formerly', 'in the past', 'once', 'earlier', 'historically', 'beforehand', 'at one time'] },
      { base: 'simultaneously', synonyms: ['concurrently', 'at the same time', 'together', 'in parallel', 'alongside', 'at once', 'jointly'] },
      { base: 'temporary', synonyms: ['short-term', 'transient', 'brief', 'fleeting', 'provisional', 'interim', 'momentary'] },
    ],
  },
  {
    category: 'স্থান / Place & Location',
    icon: '📍',
    pairs: [
      { base: 'area', synonyms: ['region', 'zone', 'district', 'territory', 'locality', 'vicinity', 'sector'] },
      { base: 'global', synonyms: ['worldwide', 'international', 'universal', 'across the globe', 'planet-wide', 'transnational', 'multinational'] },
      { base: 'urban', synonyms: ['city', 'metropolitan', 'municipal', 'civic', 'built-up', 'inner-city', 'town-based'] },
      { base: 'rural', synonyms: ['countryside', 'agricultural', 'pastoral', 'provincial', 'remote', 'non-urban', 'village-based'] },
      { base: 'widespread', synonyms: ['extensive', 'pervasive', 'prevalent', 'ubiquitous', 'far-reaching', 'rampant', 'endemic'] },
      { base: 'located', synonyms: ['situated', 'positioned', 'placed', 'established', 'found', 'set', 'based'] },
    ],
  },
  {
    category: 'স্বাস্থ্য / Health & Medicine',
    icon: '🏥',
    pairs: [
      { base: 'disease', synonyms: ['illness', 'ailment', 'condition', 'disorder', 'sickness', 'affliction', 'malady'] },
      { base: 'treat', synonyms: ['manage', 'cure', 'heal', 'remedy', 'address', 'combat', 'alleviate'] },
      { base: 'prevent', synonyms: ['avert', 'avoid', 'stop', 'impede', 'hinder', 'forestall', 'protect against'] },
      { base: 'patient', synonyms: ['individual', 'person', 'sufferer', 'case', 'subject', 'recipient', 'client'] },
      { base: 'healthy', synonyms: ['fit', 'well', 'robust', 'thriving', 'sound', 'wholesome', 'in good health'] },
      { base: 'medicine', synonyms: ['medication', 'drug', 'treatment', 'remedy', 'pharmaceutical', 'therapy', 'cure'] },
      { base: 'symptom', synonyms: ['sign', 'indicator', 'manifestation', 'signal', 'warning sign', 'evidence', 'feature'] },
    ],
  },
  {
    category: 'পরিবেশ / Environment & Nature',
    icon: '🌿',
    pairs: [
      { base: 'pollute', synonyms: ['contaminate', 'taint', 'foul', 'corrupt', 'poison', 'degrade', 'dirty'] },
      { base: 'damage', synonyms: ['harm', 'destroy', 'devastate', 'ruin', 'impair', 'degrade', 'deteriorate'] },
      { base: 'protect', synonyms: ['conserve', 'preserve', 'safeguard', 'shield', 'maintain', 'sustain', 'defend'] },
      { base: 'natural', synonyms: ['organic', 'ecological', 'environmental', 'indigenous', 'wild', 'unspoiled', 'pristine'] },
      { base: 'climate', synonyms: ['weather patterns', 'atmospheric conditions', 'environment', 'ecosystem', 'biosphere', 'climate system'] },
      { base: 'sustainable', synonyms: ['eco-friendly', 'green', 'renewable', 'long-term', 'viable', 'maintainable', 'responsible'] },
      { base: 'emission', synonyms: ['discharge', 'release', 'output', 'pollution', 'exhaust', 'effluent', 'carbon output'] },
    ],
  },
  {
    category: 'প্রযুক্তি / Technology & Science',
    icon: '💻',
    pairs: [
      { base: 'technology', synonyms: ['innovation', 'advancement', 'technique', 'machinery', 'digital tools', 'apparatus', 'system'] },
      { base: 'develop', synonyms: ['advance', 'innovate', 'progress', 'evolve', 'improve', 'enhance', 'modernise'] },
      { base: 'digital', synonyms: ['electronic', 'computerised', 'online', 'virtual', 'cyber', 'automated', 'tech-based'] },
      { base: 'invent', synonyms: ['create', 'design', 'devise', 'engineer', 'pioneer', 'originate', 'introduce'] },
      { base: 'efficient', synonyms: ['effective', 'productive', 'optimised', 'streamlined', 'capable', 'high-performing', 'functional'] },
      { base: 'artificial intelligence', synonyms: ['AI', 'machine learning', 'automation', 'robotics', 'deep learning', 'neural networks', 'smart systems'] },
      { base: 'data', synonyms: ['information', 'records', 'statistics', 'figures', 'metrics', 'input', 'content'] },
    ],
  },
  {
    category: 'শিক্ষা / Education & Learning',
    icon: '📚',
    pairs: [
      { base: 'educate', synonyms: ['teach', 'instruct', 'train', 'inform', 'enlighten', 'guide', 'mentor'] },
      { base: 'student', synonyms: ['learner', 'pupil', 'scholar', 'trainee', 'undergraduate', 'candidate', 'participant'] },
      { base: 'learn', synonyms: ['acquire', 'gain', 'absorb', 'grasp', 'master', 'comprehend', 'understand'] },
      { base: 'knowledge', synonyms: ['understanding', 'expertise', 'awareness', 'insight', 'literacy', 'competence', 'familiarity'] },
      { base: 'skill', synonyms: ['ability', 'competence', 'proficiency', 'expertise', 'capability', 'aptitude', 'talent'] },
      { base: 'curriculum', synonyms: ['syllabus', 'programme', 'course', 'plan of study', 'academic programme', 'subject matter'] },
      { base: 'academic', synonyms: ['scholarly', 'intellectual', 'educational', 'theoretical', 'university-level', 'learned', 'erudite'] },
    ],
  },
  {
    category: 'অর্থনীতি / Economy & Finance',
    icon: '💰',
    pairs: [
      { base: 'economy', synonyms: ['financial system', 'market', 'trade', 'commerce', 'industry', 'fiscal system', 'economic structure'] },
      { base: 'invest', synonyms: ['fund', 'finance', 'support', 'allocate resources', 'contribute capital', 'put money into', 'bankroll'] },
      { base: 'profit', synonyms: ['revenue', 'gain', 'income', 'earnings', 'return', 'surplus', 'yield'] },
      { base: 'poverty', synonyms: ['deprivation', 'hardship', 'destitution', 'financial difficulty', 'low income', 'inequality', 'disadvantage'] },
      { base: 'grow (economy)', synonyms: ['expand', 'develop', 'strengthen', 'flourish', 'advance', 'thrive', 'progress'] },
      { base: 'cost', synonyms: ['expense', 'expenditure', 'outlay', 'price', 'fee', 'charge', 'financial burden'] },
      { base: 'trade', synonyms: ['commerce', 'exchange', 'import/export', 'business', 'transaction', 'dealings', 'economic activity'] },
    ],
  },
  {
    category: 'সমাজ / Society & Culture',
    icon: '🌍',
    pairs: [
      { base: 'society', synonyms: ['community', 'population', 'public', 'civilization', 'nation', 'social fabric', 'the masses'] },
      { base: 'tradition', synonyms: ['custom', 'heritage', 'culture', 'practice', 'convention', 'norm', 'ritual'] },
      { base: 'equality', synonyms: ['fairness', 'equity', 'justice', 'impartiality', 'equal rights', 'parity', 'balance'] },
      { base: 'diverse', synonyms: ['varied', 'multicultural', 'heterogeneous', 'mixed', 'pluralistic', 'wide-ranging', 'assorted'] },
      { base: 'community', synonyms: ['neighbourhood', 'group', 'population', 'residents', 'citizens', 'local people', 'social group'] },
      { base: 'norm', synonyms: ['standard', 'convention', 'expectation', 'rule', 'practice', 'code', 'accepted behaviour'] },
      { base: 'impact (social)', synonyms: ['influence', 'effect', 'consequence', 'implication', 'bearing', 'repercussion', 'significance'] },
    ],
  },
  {
    category: 'সরকার / Government & Policy',
    icon: '🏛️',
    pairs: [
      { base: 'government', synonyms: ['authorities', 'administration', 'state', 'ruling body', 'regime', 'council', 'legislature'] },
      { base: 'policy', synonyms: ['regulation', 'law', 'legislation', 'guideline', 'measure', 'strategy', 'directive'] },
      { base: 'implement', synonyms: ['enforce', 'apply', 'introduce', 'execute', 'put in place', 'carry out', 'establish'] },
      { base: 'ban', synonyms: ['prohibit', 'restrict', 'outlaw', 'forbid', 'prevent', 'bar', 'disallow'] },
      { base: 'fund', synonyms: ['finance', 'subsidise', 'support', 'allocate', 'sponsor', 'grant', 'invest in'] },
      { base: 'reform', synonyms: ['overhaul', 'restructure', 'revise', 'improve', 'update', 'transform', 'amend'] },
      { base: 'authority', synonyms: ['power', 'jurisdiction', 'control', 'governance', 'oversight', 'mandate', 'command'] },
    ],
  },
  {
    category: 'পরিবহন / Transport & Infrastructure',
    icon: '🚆',
    pairs: [
      { base: 'transport', synonyms: ['travel', 'transit', 'commute', 'transportation', 'mobility', 'conveyance', 'movement'] },
      { base: 'build', synonyms: ['construct', 'develop', 'establish', 'erect', 'create', 'put up', 'set up'] },
      { base: 'congestion', synonyms: ['traffic jam', 'gridlock', 'overcrowding', 'bottleneck', 'blockage', 'traffic buildup', 'overload'] },
      { base: 'road', synonyms: ['highway', 'motorway', 'route', 'pathway', 'street', 'thoroughfare', 'carriageway'] },
      { base: 'infrastructure', synonyms: ['facilities', 'system', 'network', 'framework', 'public works', 'utilities', 'services'] },
      { base: 'connect', synonyms: ['link', 'join', 'integrate', 'unite', 'bridge', 'network', 'bind'] },
    ],
  },
  {
    category: 'খাদ্য / Food & Nutrition',
    icon: '🥗',
    pairs: [
      { base: 'nutritious', synonyms: ['healthy', 'wholesome', 'nourishing', 'balanced', 'fortified', 'beneficial', 'rich in nutrients'] },
      { base: 'consume', synonyms: ['eat', 'intake', 'ingest', 'devour', 'feed on', 'take in', 'partake of'] },
      { base: 'diet', synonyms: ['nutrition', 'food intake', 'eating habits', 'food consumption', 'meal plan', 'sustenance', 'nourishment'] },
      { base: 'shortage', synonyms: ['scarcity', 'deficiency', 'lack', 'insufficiency', 'deficit', 'dearth', 'inadequacy'] },
      { base: 'produce', synonyms: ['grow', 'cultivate', 'harvest', 'yield', 'supply', 'generate', 'manufacture'] },
      { base: 'obesity', synonyms: ['overweight', 'excess weight', 'adiposity', 'being overweight', 'weight problem', 'high body mass'] },
    ],
  },
  {
    category: 'যোগাযোগ / Communication & Language',
    icon: '💬',
    pairs: [
      { base: 'communicate', synonyms: ['convey', 'express', 'relay', 'transmit', 'articulate', 'share', 'exchange'] },
      { base: 'language', synonyms: ['tongue', 'dialect', 'speech', 'verbal expression', 'communication system', 'idiom', 'vernacular'] },
      { base: 'inform', synonyms: ['notify', 'advise', 'brief', 'update', 'enlighten', 'educate', 'tell'] },
      { base: 'media', synonyms: ['press', 'broadcast', 'news outlets', 'journalism', 'publications', 'platform', 'channels'] },
      { base: 'discuss', synonyms: ['debate', 'examine', 'deliberate', 'explore', 'address', 'consider', 'talk about'] },
      { base: 'persuade', synonyms: ['convince', 'influence', 'sway', 'urge', 'encourage', 'motivate', 'argue for'] },
      { base: 'describe', synonyms: ['depict', 'portray', 'outline', 'characterise', 'illustrate', 'explain', 'detail'] },
    ],
  },
  {
    category: 'আবেগ / Emotions & Attitudes',
    icon: '😊',
    pairs: [
      { base: 'concerned', synonyms: ['worried', 'troubled', 'anxious', 'apprehensive', 'alarmed', 'uneasy', 'distressed'] },
      { base: 'satisfied', synonyms: ['content', 'pleased', 'fulfilled', 'gratified', 'happy', 'comfortable', 'contented'] },
      { base: 'enthusiastic', synonyms: ['eager', 'passionate', 'keen', 'motivated', 'committed', 'dedicated', 'fervent'] },
      { base: 'critical', synonyms: ['sceptical', 'doubtful', 'disapproving', 'negative', 'cynical', 'opposed', 'questioning'] },
      { base: 'optimistic', synonyms: ['hopeful', 'positive', 'confident', 'assured', 'expectant', 'encouraged', 'buoyant'] },
      { base: 'reluctant', synonyms: ['unwilling', 'hesitant', 'resistant', 'opposed', 'disinclined', 'averse', 'unenthusiastic'] },
    ],
  },
  {
    category: 'সাফল্য / Success & Failure',
    icon: '🏆',
    pairs: [
      { base: 'succeed', synonyms: ['achieve', 'accomplish', 'attain', 'reach', 'fulfil', 'realise', 'excel'] },
      { base: 'fail', synonyms: ['fall short', 'be unsuccessful', 'collapse', 'falter', 'underperform', 'miss the mark', 'stumble'] },
      { base: 'achieve', synonyms: ['accomplish', 'attain', 'reach', 'gain', 'secure', 'obtain', 'deliver'] },
      { base: 'obstacle', synonyms: ['barrier', 'challenge', 'difficulty', 'hindrance', 'impediment', 'hurdle', 'setback'] },
      { base: 'progress', synonyms: ['advancement', 'development', 'improvement', 'growth', 'headway', 'forward movement', 'stride'] },
      { base: 'effective', synonyms: ['successful', 'productive', 'efficient', 'fruitful', 'impactful', 'powerful', 'influential'] },
    ],
  },
  {
    category: 'ইতিবাচক / Positive & Beneficial',
    icon: '✅',
    pairs: [
      { base: 'benefit', synonyms: ['advantage', 'gain', 'merit', 'positive aspect', 'plus', 'asset', 'reward'] },
      { base: 'improve', synonyms: ['enhance', 'boost', 'upgrade', 'strengthen', 'advance', 'refine', 'optimise'] },
      { base: 'useful', synonyms: ['valuable', 'practical', 'constructive', 'productive', 'helpful', 'worthwhile', 'advantageous'] },
      { base: 'opportunity', synonyms: ['chance', 'prospect', 'opening', 'possibility', 'potential', 'occasion', 'scope'] },
      { base: 'significant', synonyms: ['notable', 'remarkable', 'considerable', 'substantial', 'meaningful', 'profound', 'noteworthy'] },
      { base: 'innovative', synonyms: ['creative', 'novel', 'pioneering', 'groundbreaking', 'original', 'cutting-edge', 'forward-thinking'] },
    ],
  },
  {
    category: 'নেতিবাচক / Negative & Harmful',
    icon: '⚠️',
    pairs: [
      { base: 'harmful', synonyms: ['damaging', 'detrimental', 'destructive', 'adverse', 'injurious', 'hazardous', 'negative'] },
      { base: 'risk', synonyms: ['danger', 'threat', 'hazard', 'peril', 'vulnerability', 'concern', 'exposure'] },
      { base: 'worsen', synonyms: ['deteriorate', 'aggravate', 'compound', 'exacerbate', 'intensify', 'decline', 'degrade'] },
      { base: 'drawback', synonyms: ['disadvantage', 'downside', 'limitation', 'weakness', 'shortcoming', 'flaw', 'negative aspect'] },
      { base: 'serious', synonyms: ['severe', 'grave', 'critical', 'acute', 'significant', 'alarming', 'dire'] },
      { base: 'fail (to address)', synonyms: ['neglect', 'overlook', 'disregard', 'ignore', 'underestimate', 'dismiss', 'undervalue'] },
    ],
  },
  {
    category: 'Task 2 Essay Words',
    icon: '✍️',
    pairs: [
      { base: 'believe', synonyms: ['think', 'consider', 'feel', 'hold the view', 'maintain', 'argue', 'take the position that'] },
      { base: 'discuss', synonyms: ['examine', 'consider', 'explore', 'address', 'analyse', 'evaluate', 'look at'] },
      { base: 'extent', synonyms: ['degree', 'level', 'measure', 'proportion', 'scale', 'scope', 'magnitude'] },
      { base: 'viewpoint', synonyms: ['perspective', 'opinion', 'stance', 'position', 'argument', 'standpoint', 'outlook'] },
      { base: 'outweigh', synonyms: ['surpass', 'exceed', 'override', 'dominate', 'be greater than', 'offset', 'overshadow'] },
      { base: 'justify', synonyms: ['warrant', 'validate', 'support', 'defend', 'rationalise', 'excuse', 'substantiate'] },
      { base: 'solution', synonyms: ['answer', 'resolution', 'remedy', 'approach', 'measure', 'strategy', 'response'] },
    ],
  },
  {
    category: 'IELTS Reading Keywords',
    icon: '📖',
    pairs: [
      { base: 'suggest', synonyms: ['imply', 'indicate', 'propose', 'infer', 'point to', 'hint at', 'allude to'] },
      { base: 'according to', synonyms: ['based on', 'as stated by', 'as reported by', 'in line with', 'consistent with', 'as noted by'] },
      { base: 'claim', synonyms: ['assert', 'argue', 'state', 'contend', 'maintain', 'allege', 'declare'] },
      { base: 'contrast', synonyms: ['differ', 'oppose', 'conflict with', 'be at odds with', 'diverge from', 'stand apart from'] },
      { base: 'passage', synonyms: ['text', 'extract', 'excerpt', 'section', 'article', 'reading', 'piece'] },
      { base: 'author', synonyms: ['writer', 'researcher', 'scholar', 'analyst', 'commentator', 'expert', 'academic'] },
    ],
  },
  {
    category: 'Listening Keywords',
    icon: '🎧',
    pairs: [
      { base: 'mention', synonyms: ['refer to', 'note', 'state', 'indicate', 'point out', 'specify', 'name'] },
      { base: 'confirm', synonyms: ['verify', 'clarify', 'assure', 'affirm', 'check', 'ensure', 'validate'] },
      { base: 'schedule', synonyms: ['timetable', 'plan', 'agenda', 'programme', 'timetable', 'roster', 'calendar'] },
      { base: 'available', synonyms: ['accessible', 'open', 'free', 'obtainable', 'on offer', 'ready', 'at hand'] },
      { base: 'locate', synonyms: ['find', 'identify', 'spot', 'pinpoint', 'discover', 'detect', 'come across'] },
      { base: 'option', synonyms: ['choice', 'alternative', 'possibility', 'selection', 'preference', 'avenue', 'route'] },
    ],
  },
  {
    category: 'পুনরাবৃত্তি / Frequency Words',
    icon: '🔄',
    pairs: [
      { base: 'always', synonyms: ['invariably', 'consistently', 'constantly', 'perpetually', 'universally', 'without exception', 'unfailingly'] },
      { base: 'often', synonyms: ['frequently', 'regularly', 'commonly', 'repeatedly', 'habitually', 'generally', 'in many cases'] },
      { base: 'sometimes', synonyms: ['occasionally', 'at times', 'in some cases', 'now and then', 'periodically', 'intermittently', 'on occasion'] },
      { base: 'rarely', synonyms: ['seldom', 'infrequently', 'uncommonly', 'hardly ever', 'barely', 'not often', 'on rare occasions'] },
      { base: 'never', synonyms: ['not at all', 'at no point', 'under no circumstances', 'in no instance', 'not once', 'by no means'] },
      { base: 'increasingly', synonyms: ['more and more', 'progressively', 'to a greater extent', 'growing', 'ever more', 'at an increasing rate'] },
    ],
  },
  {
    category: 'মাত্রা / Degree & Intensity Words',
    icon: '📊',
    pairs: [
      { base: 'very', synonyms: ['extremely', 'highly', 'considerably', 'substantially', 'significantly', 'remarkably', 'exceptionally'] },
      { base: 'slightly', synonyms: ['marginally', 'modestly', 'somewhat', 'mildly', 'to a minor degree', 'barely', 'a little'] },
      { base: 'largely', synonyms: ['mainly', 'predominantly', 'primarily', 'chiefly', 'mostly', 'for the most part', 'to a great extent'] },
      { base: 'completely', synonyms: ['entirely', 'wholly', 'fully', 'totally', 'absolutely', 'thoroughly', 'utterly'] },
      { base: 'particularly', synonyms: ['especially', 'notably', 'specifically', 'in particular', 'above all', 'most importantly', 'specifically'] },
      { base: 'relatively', synonyms: ['comparatively', 'somewhat', 'fairly', 'moderately', 'in comparison', 'proportionally', 'to some degree'] },
    ],
  },
  {
    category: 'যুক্তি / Opinion & Argument Words',
    icon: '🗣️',
    pairs: [
      { base: 'opinion', synonyms: ['view', 'perspective', 'standpoint', 'position', 'belief', 'judgement', 'assessment'] },
      { base: 'evidence', synonyms: ['proof', 'support', 'data', 'documentation', 'corroboration', 'substantiation', 'verification'] },
      { base: 'reason', synonyms: ['rationale', 'justification', 'basis', 'ground', 'explanation', 'motive', 'logic'] },
      { base: 'counter-argument', synonyms: ['rebuttal', 'objection', 'opposition', 'opposing view', 'contrary position', 'alternative view', 'refutation'] },
      { base: 'logical', synonyms: ['rational', 'reasonable', 'sound', 'coherent', 'well-reasoned', 'valid', 'sensible'] },
      { base: 'emphasise', synonyms: ['stress', 'highlight', 'underline', 'underscore', 'accentuate', 'draw attention to', 'prioritise'] },
    ],
  },
  {
    category: 'মিল / Similarity & Difference Words',
    icon: '🔍',
    pairs: [
      { base: 'in common', synonyms: ['shared', 'mutual', 'alike', 'comparable', 'equivalent', 'parallel', 'corresponding'] },
      { base: 'vary', synonyms: ['differ', 'diverge', 'range', 'change', 'fluctuate', 'contrast', 'differ from one another'] },
      { base: 'match', synonyms: ['correspond to', 'align with', 'correlate with', 'fit', 'mirror', 'echo', 'tally with'] },
      { base: 'unique', synonyms: ['distinctive', 'individual', 'particular', 'specific', 'singular', 'one-of-a-kind', 'unparalleled'] },
      { base: 'resemble', synonyms: ['be similar to', 'be comparable to', 'share features with', 'mirror', 'parallel', 'approximate'] },
      { base: 'gap', synonyms: ['difference', 'disparity', 'discrepancy', 'divide', 'inequality', 'contrast', 'gulf'] },
    ],
  },
  {
    category: 'সংখ্যা / Numbers & Statistics',
    icon: '📈',
    pairs: [
      { base: 'proportion', synonyms: ['percentage', 'fraction', 'ratio', 'share', 'portion', 'segment', 'part'] },
      { base: 'majority', synonyms: ['most', 'the bulk', 'the greater part', 'over half', 'a large number', 'the bulk of', 'a predominant share'] },
      { base: 'approximately', synonyms: ['roughly', 'around', 'about', 'nearly', 'almost', 'in the region of', 'close to'] },
      { base: 'double', synonyms: ['twice as much', 'twofold', 'multiply by two', '100% increase', 'two times', 'double the amount'] },
      { base: 'average', synonyms: ['mean', 'median', 'typical', 'standard', 'usual', 'norm', 'middle value'] },
      { base: 'significant number', synonyms: ['large proportion', 'considerable amount', 'substantial figure', 'high percentage', 'notable quantity', 'great deal'] },
    ],
  },
  {
    category: 'কর্মসংস্থান / Work & Employment',
    icon: '💼',
    pairs: [
      { base: 'job', synonyms: ['occupation', 'profession', 'career', 'role', 'position', 'post', 'vocation'] },
      { base: 'unemployed', synonyms: ['out of work', 'jobless', 'without employment', 'redundant', 'laid off', 'workless', 'idle'] },
      { base: 'employer', synonyms: ['company', 'organisation', 'business', 'firm', 'enterprise', 'corporation', 'institution'] },
      { base: 'workforce', synonyms: ['labour force', 'employees', 'staff', 'workers', 'personnel', 'human resources', 'manpower'] },
      { base: 'salary', synonyms: ['wage', 'pay', 'income', 'earnings', 'remuneration', 'compensation', 'stipend'] },
      { base: 'skilled', synonyms: ['qualified', 'trained', 'experienced', 'proficient', 'competent', 'expert', 'capable'] },
      { base: 'productive', synonyms: ['efficient', 'output-driven', 'effective', 'high-performing', 'results-oriented', 'industrious', 'diligent'] },
    ],
  },
  {
    category: 'আবাসন / Housing & Urbanisation',
    icon: '🏙️',
    pairs: [
      { base: 'housing', synonyms: ['accommodation', 'shelter', 'residence', 'dwelling', 'home', 'abode', 'living space'] },
      { base: 'urbanisation', synonyms: ['city growth', 'urban expansion', 'metropolitan development', 'migration to cities', 'urban sprawl', 'city development'] },
      { base: 'overcrowded', synonyms: ['densely populated', 'congested', 'packed', 'overpopulated', 'crammed', 'full to capacity', 'teeming'] },
      { base: 'affordable', synonyms: ['low-cost', 'economical', 'cheap', 'accessible', 'within reach', 'reasonably priced', 'inexpensive'] },
      { base: 'migrate', synonyms: ['move', 'relocate', 'settle', 'emigrate', 'immigrate', 'resettle', 'transfer'] },
      { base: 'facility', synonyms: ['amenity', 'service', 'infrastructure', 'provision', 'resource', 'equipment', 'utilities'] },
    ],
  },
  {
    category: 'শক্তি / Energy & Resources',
    icon: '⚡',
    pairs: [
      { base: 'energy', synonyms: ['power', 'fuel', 'electricity', 'resource', 'capacity', 'supply', 'force'] },
      { base: 'renewable', synonyms: ['sustainable', 'clean', 'green', 'alternative', 'eco-friendly', 'non-fossil', 'replenishable'] },
      { base: 'fossil fuel', synonyms: ['coal', 'oil', 'gas', 'non-renewable energy', 'carbon-based fuel', 'petroleum', 'conventional fuel'] },
      { base: 'consume (energy)', synonyms: ['use', 'utilise', 'deplete', 'draw on', 'expend', 'burn', 'spend'] },
      { base: 'scarce', synonyms: ['limited', 'finite', 'depleted', 'short in supply', 'insufficient', 'rare', 'in short supply'] },
      { base: 'conservation', synonyms: ['preservation', 'protection', 'saving', 'efficient use', 'reduction', 'sustainability', 'careful management'] },
    ],
  },
  {
    category: 'বৈশ্বিক সমস্যা / Global Issues',
    icon: '🌐',
    pairs: [
      { base: 'globalisation', synonyms: ['internationalisation', 'global integration', 'world interconnectedness', 'cross-border exchange', 'economic interdependence'] },
      { base: 'inequality', synonyms: ['disparity', 'gap', 'imbalance', 'unfairness', 'injustice', 'divide', 'discrimination'] },
      { base: 'conflict', synonyms: ['war', 'dispute', 'tension', 'crisis', 'instability', 'hostility', 'confrontation'] },
      { base: 'migration', synonyms: ['movement of people', 'relocation', 'displacement', 'immigration', 'emigration', 'population shift', 'refugee movement'] },
      { base: 'cooperation', synonyms: ['collaboration', 'partnership', 'joint effort', 'alliance', 'coordination', 'teamwork', 'multilateral action'] },
      { base: 'crisis', synonyms: ['emergency', 'disaster', 'catastrophe', 'threat', 'challenge', 'calamity', 'breakdown'] },
    ],
  },
  {
    category: 'গবেষণা পদ্ধতি / Research Methods',
    icon: '📋',
    pairs: [
      { base: 'survey', synonyms: ['questionnaire', 'poll', 'interview study', 'data collection', 'inquiry', 'assessment', 'evaluation'] },
      { base: 'experiment', synonyms: ['trial', 'test', 'controlled study', 'investigation', 'procedure', 'scientific study', 'empirical study'] },
      { base: 'sample', synonyms: ['group', 'subset', 'cohort', 'participants', 'subjects', 'test group', 'representative group'] },
      { base: 'hypothesis', synonyms: ['theory', 'assumption', 'proposition', 'claim', 'premise', 'supposition', 'conjecture'] },
      { base: 'variable', synonyms: ['factor', 'element', 'component', 'parameter', 'condition', 'aspect', 'consideration'] },
      { base: 'objective', synonyms: ['aim', 'goal', 'purpose', 'target', 'intention', 'focus', 'mission'] },
    ],
  },
  {
    category: 'তথ্য ও প্রমাণ / Data & Evidence',
    icon: '📊',
    pairs: [
      { base: 'show', synonyms: ['demonstrate', 'reveal', 'indicate', 'illustrate', 'highlight', 'suggest', 'reflect'] },
      { base: 'source', synonyms: ['reference', 'citation', 'authority', 'origin', 'basis', 'foundation', 'documentation'] },
      { base: 'reliable', synonyms: ['trustworthy', 'credible', 'valid', 'accurate', 'dependable', 'authentic', 'sound'] },
      { base: 'significant (data)', synonyms: ['notable', 'meaningful', 'substantial', 'considerable', 'important', 'marked', 'relevant'] },
      { base: 'trend', synonyms: ['pattern', 'tendency', 'direction', 'movement', 'shift', 'development', 'trajectory'] },
      { base: 'correlation', synonyms: ['relationship', 'connection', 'association', 'link', 'correspondence', 'pattern', 'interrelation'] },
      { base: 'measure', synonyms: ['quantify', 'calculate', 'assess', 'evaluate', 'gauge', 'determine', 'record'] },
    ],
  },
  {
    category: 'Academic Abstract Nouns',
    icon: '🧠',
    pairs: [
      { base: 'development', synonyms: ['advancement', 'progress', 'evolution', 'growth', 'improvement', 'expansion', 'transformation'] },
      { base: 'implication', synonyms: ['consequence', 'significance', 'impact', 'meaning', 'suggestion', 'repercussion', 'ramification'] },
      { base: 'phenomenon', synonyms: ['occurrence', 'event', 'trend', 'situation', 'issue', 'observation', 'circumstance'] },
      { base: 'framework', synonyms: ['structure', 'model', 'system', 'approach', 'paradigm', 'scheme', 'foundation'] },
      { base: 'concept', synonyms: ['idea', 'notion', 'principle', 'theory', 'proposition', 'construct', 'perspective'] },
      { base: 'context', synonyms: ['background', 'setting', 'circumstances', 'conditions', 'environment', 'situation', 'frame of reference'] },
    ],
  },
  {
    category: 'প্রভাব / Verbs of Influence',
    icon: '🎯',
    pairs: [
      { base: 'influence', synonyms: ['affect', 'shape', 'impact', 'determine', 'govern', 'drive', 'mould'] },
      { base: 'encourage', synonyms: ['promote', 'stimulate', 'motivate', 'inspire', 'foster', 'nurture', 'facilitate'] },
      { base: 'discourage', synonyms: ['deter', 'inhibit', 'prevent', 'hinder', 'suppress', 'limit', 'restrict'] },
      { base: 'force', synonyms: ['compel', 'oblige', 'require', 'push', 'drive', 'pressurise', 'coerce'] },
      { base: 'allow', synonyms: ['permit', 'enable', 'facilitate', 'provide for', 'authorise', 'empower', 'give rise to'] },
      { base: 'lead to', synonyms: ['result in', 'cause', 'bring about', 'produce', 'generate', 'trigger', 'give rise to'] },
    ],
  },
  {
    category: 'শর্ত / Condition & Possibility',
    icon: '🔀',
    pairs: [
      { base: 'if', synonyms: ['provided that', 'as long as', 'on the condition that', 'assuming', 'given that', 'in the event that', 'should'] },
      { base: 'possible', synonyms: ['feasible', 'viable', 'achievable', 'plausible', 'likely', 'realistic', 'conceivable'] },
      { base: 'likely', synonyms: ['probable', 'expected', 'anticipated', 'predictable', 'foreseeable', 'potential', 'prospective'] },
      { base: 'unlikely', synonyms: ['improbable', 'doubtful', 'uncertain', 'questionable', 'far-fetched', 'remote', 'not probable'] },
      { base: 'unless', synonyms: ['except if', 'only if not', 'without', 'in the absence of', 'but for', 'were it not for'] },
      { base: 'depend on', synonyms: ['hinge on', 'rely on', 'be contingent on', 'be determined by', 'rest on', 'vary according to', 'be subject to'] },
    ],
  },
  {
    category: 'বৈসাদৃশ্য / Contrast & Concession',
    icon: '↔️',
    pairs: [
      { base: 'on the other hand', synonyms: ['conversely', 'in contrast', 'alternatively', 'by contrast', 'that said', 'then again', 'at the same time'] },
      { base: 'even though', synonyms: ['although', 'despite the fact that', 'in spite of', 'notwithstanding', 'while', 'whilst', 'regardless of the fact'] },
      { base: 'admit', synonyms: ['concede', 'acknowledge', 'accept', 'grant', 'recognise', 'allow', 'agree'] },
      { base: 'yet', synonyms: ['but', 'still', 'however', 'nonetheless', 'nevertheless', 'even so', 'that said'] },
      { base: 'despite', synonyms: ['in spite of', 'notwithstanding', 'even with', 'regardless of', 'irrespective of', 'with all'] },
      { base: 'whereas', synonyms: ['while', 'on the other hand', 'in contrast to', 'as opposed to', 'but', 'by comparison', 'conversely'] },
    ],
  },
  {
    category: 'সংযোজন / Additions & Furthermore',
    icon: '➕',
    pairs: [
      { base: 'also', synonyms: ['in addition', 'furthermore', 'moreover', 'as well', 'too', 'additionally', 'on top of this'] },
      { base: 'not only...but also', synonyms: ['in addition to', 'beyond', 'as well as', 'coupled with', 'together with', 'along with', 'plus'] },
      { base: 'besides', synonyms: ['in addition to', 'apart from', 'other than', 'beyond', 'over and above', 'as well as', 'including'] },
      { base: 'expand', synonyms: ['extend', 'broaden', 'widen', 'enlarge', 'increase', 'elaborate on', 'build on'] },
      { base: 'supplement', synonyms: ['add to', 'complement', 'enhance', 'support', 'bolster', 'reinforce', 'augment'] },
      { base: 'include', synonyms: ['incorporate', 'encompass', 'cover', 'contain', 'involve', 'comprise', 'embrace'] },
    ],
  },
  {
    category: 'বিশ্লেষণ / Analysis & Evaluation',
    icon: '🧩',
    pairs: [
      { base: 'evaluate', synonyms: ['assess', 'judge', 'appraise', 'review', 'examine', 'consider', 'measure'] },
      { base: 'interpret', synonyms: ['explain', 'understand', 'read', 'translate', 'clarify', 'account for', 'make sense of'] },
      { base: 'compare', synonyms: ['contrast', 'juxtapose', 'weigh up', 'set against', 'measure against', 'examine alongside'] },
      { base: 'highlight', synonyms: ['emphasise', 'point out', 'draw attention to', 'accentuate', 'stress', 'underline', 'focus on'] },
      { base: 'conclude', synonyms: ['determine', 'infer', 'deduce', 'derive', 'establish', 'find', 'judge'] },
      { base: 'question', synonyms: ['challenge', 'query', 'dispute', 'doubt', 'interrogate', 'probe', 'examine critically'] },
    ],
  },
  {
    category: 'সম্পর্ক / Relationships & Connections',
    icon: '🔗',
    pairs: [
      { base: 'relate to', synonyms: ['connect to', 'link to', 'associate with', 'correspond to', 'pertain to', 'be relevant to', 'apply to'] },
      { base: 'depend on', synonyms: ['rely on', 'be contingent on', 'hinge on', 'be subject to', 'rest on', 'require', 'need'] },
      { base: 'interact', synonyms: ['engage with', 'relate to', 'communicate', 'connect', 'work with', 'collaborate', 'interface'] },
      { base: 'influence each other', synonyms: ['are interrelated', 'are interdependent', 'affect one another', 'are interconnected', 'are linked', 'correlate'] },
      { base: 'involve', synonyms: ['include', 'encompass', 'concern', 'affect', 'relate to', 'pertain to', 'entail'] },
      { base: 'apply to', synonyms: ['be relevant to', 'be applicable to', 'concern', 'affect', 'pertain to', 'hold for', 'extend to'] },
    ],
  },
  {
    category: 'গুণ / Qualities & Characteristics',
    icon: '⭐',
    pairs: [
      { base: 'complex', synonyms: ['complicated', 'intricate', 'multifaceted', 'sophisticated', 'nuanced', 'elaborate', 'detailed'] },
      { base: 'flexible', synonyms: ['adaptable', 'versatile', 'adjustable', 'dynamic', 'open', 'fluid', 'variable'] },
      { base: 'diverse', synonyms: ['varied', 'wide-ranging', 'assorted', 'manifold', 'multifarious', 'heterogeneous', 'eclectic'] },
      { base: 'transparent', synonyms: ['open', 'clear', 'honest', 'accountable', 'straightforward', 'accessible', 'visible'] },
      { base: 'accurate', synonyms: ['precise', 'correct', 'exact', 'reliable', 'true', 'valid', 'faithful'] },
      { base: 'consistent', synonyms: ['steady', 'regular', 'stable', 'uniform', 'constant', 'coherent', 'persistent'] },
    ],
  },
  {
    category: 'প্রস্তাব / Recommendations & Suggestions',
    icon: '💡',
    pairs: [
      { base: 'recommend', synonyms: ['suggest', 'propose', 'advise', 'advocate', 'urge', 'call for', 'put forward'] },
      { base: 'should', synonyms: ['ought to', 'must', 'needs to', 'is required to', 'is advised to', 'would be wise to', 'is encouraged to'] },
      { base: 'necessary', synonyms: ['essential', 'vital', 'crucial', 'required', 'imperative', 'indispensable', 'fundamental'] },
      { base: 'address', synonyms: ['tackle', 'deal with', 'handle', 'resolve', 'attend to', 'manage', 'respond to'] },
      { base: 'measure', synonyms: ['step', 'action', 'initiative', 'strategy', 'approach', 'policy', 'intervention'] },
      { base: 'priority', synonyms: ['main concern', 'focus', 'key issue', 'most important', 'urgent matter', 'central goal', 'top agenda'] },
    ],
  },
  {
    category: 'উদ্দেশ্য / Purpose & Goals',
    icon: '🎯',
    pairs: [
      { base: 'aim', synonyms: ['goal', 'objective', 'purpose', 'target', 'intention', 'ambition', 'aspiration'] },
      { base: 'intend', synonyms: ['plan', 'seek', 'wish', 'hope', 'mean', 'desire', 'aspire'] },
      { base: 'in order to', synonyms: ['so as to', 'with the aim of', 'for the purpose of', 'to ensure', 'with the intention of', 'so that'] },
      { base: 'seek', synonyms: ['pursue', 'endeavour', 'attempt', 'strive for', 'work towards', 'look for', 'try to achieve'] },
      { base: 'achieve', synonyms: ['accomplish', 'realise', 'attain', 'fulfil', 'reach', 'complete', 'bring about'] },
      { base: 'focus on', synonyms: ['concentrate on', 'prioritise', 'centre on', 'target', 'address', 'emphasise', 'direct attention to'] },
    ],
  },
  {
    category: 'বিবরণ / Description & Definition',
    icon: '📝',
    pairs: [
      { base: 'define', synonyms: ['explain', 'clarify', 'describe', 'specify', 'outline', 'characterise', 'identify'] },
      { base: 'refer to', synonyms: ['describe', 'denote', 'mean', 'relate to', 'apply to', 'indicate', 'stand for'] },
      { base: 'term', synonyms: ['word', 'phrase', 'concept', 'expression', 'label', 'name', 'designation'] },
      { base: 'broadly', synonyms: ['generally', 'in general terms', 'widely', 'for the most part', 'largely', 'overall', 'on the whole'] },
      { base: 'specifically', synonyms: ['in particular', 'notably', 'especially', 'precisely', 'exactly', 'in detail', 'explicitly'] },
      { base: 'example', synonyms: ['instance', 'case', 'illustration', 'demonstration', 'specimen', 'sample', 'model'] },
    ],
  },
  {
    category: 'পরিবর্তনের ধরন / Types of Change',
    icon: '🔃',
    pairs: [
      { base: 'transform', synonyms: ['convert', 'reshape', 'revolutionise', 'alter significantly', 'overhaul', 'reconstruct', 'reinvent'] },
      { base: 'shift', synonyms: ['move', 'transition', 'change direction', 'transfer', 'evolve', 'pivot', 'reorient'] },
      { base: 'adapt', synonyms: ['adjust', 'modify', 'accommodate', 'respond to', 'conform', 'tailor', 'reshape'] },
      { base: 'replace', synonyms: ['substitute', 'supersede', 'take the place of', 'exchange', 'swap out', 'displace', 'supplant'] },
      { base: 'stabilise', synonyms: ['maintain', 'balance', 'level off', 'settle', 'remain constant', 'plateau', 'reach equilibrium'] },
      { base: 'fluctuate', synonyms: ['vary', 'change', 'oscillate', 'rise and fall', 'shift', 'be unstable', 'be volatile'] },
    ],
  },
  {
    category: 'তুলনামূলক কাঠামো / Comparative Structures',
    icon: '🔁',
    pairs: [
      { base: 'more than', synonyms: ['greater than', 'higher than', 'exceeding', 'above', 'over', 'surpassing', 'in excess of'] },
      { base: 'less than', synonyms: ['fewer than', 'lower than', 'below', 'under', 'not as much as', 'smaller than', 'inferior to'] },
      { base: 'as...as', synonyms: ['equally', 'at the same rate', 'to the same degree', 'comparably', 'identically', 'proportionally'] },
      { base: 'the most', synonyms: ['the greatest', 'the highest', 'the largest', 'the most significant', 'predominantly', 'above all', 'most of all'] },
      { base: 'the least', synonyms: ['the smallest', 'the lowest', 'the minimum', 'to the slightest degree', 'barely', 'the fewest'] },
      { base: 'better than', synonyms: ['superior to', 'more effective than', 'preferable to', 'more successful than', 'ahead of', 'outperforming'] },
    ],
  },
];
