import type { TechniqueId } from './paraphraseData';

export interface PracticeSentence {
    text: string;
    hint: string;
    technique: TechniqueId;
    source?: string;
}

export const PRACTICE_SENTENCES: PracticeSentence[] = [
    { text: 'Scientists have found that regular exercise helps prevent heart disease.', hint: 'Try replacing scientists, found, regular, exercise, and heart disease with synonyms.', technique: 'synonym' },
    { text: 'The government introduced new laws to reduce pollution.', hint: 'Try converting this sentence to passive voice.', technique: 'active_passive' },
    { text: 'The company decided to expand its operations overseas.', hint: 'Convert the verb "decided" into a noun phrase (nominalization).', technique: 'nominalization' },
    { text: 'Although prices rose sharply, people continued to buy luxury goods.', hint: 'Try using "Despite" followed by a noun phrase instead of "Although".', technique: 'clause_restructure' },
    { text: 'The solution was not effective.', hint: 'Add a negative prefix to "effective" to avoid using "not".', technique: 'word_form' },
    { text: 'The economy did not grow last year.', hint: 'Replace "did not grow" with its antonym.', technique: 'antonym_negation' },
    { text: 'Researchers discovered that a lack of sleep impairs cognitive function.', hint: 'Try replacing all key words with synonyms.', technique: 'synonym' },
    { text: 'The new policy was approved by the board of directors.', hint: 'Convert this passive sentence to active voice.', technique: 'active_passive' },
    { text: 'The population grew rapidly after the industrial revolution.', hint: 'Convert "grew rapidly" into a noun phrase using nominalization.', technique: 'nominalization' },
    { text: 'Because the weather was bad, the event was cancelled.', hint: 'Use "Due to" + noun phrase instead of "Because".', technique: 'clause_restructure' },
    { text: 'His argument was not logical.', hint: 'Use the prefix "il-" to create a single word meaning "not logical".', technique: 'word_form' },
    { text: 'The team did not win the championship this year.', hint: 'Replace "did not win" with a single antonym verb.', technique: 'antonym_negation' },
    { text: 'Many students struggle with time management during exams.', hint: 'Replace key words: many, struggle, time management, during, exams.', technique: 'synonym' },
    { text: 'The scientist conducted the experiment carefully.', hint: 'Convert to passive: the experiment was...', technique: 'active_passive' },
    { text: 'People consume a lot of energy when they use air conditioning.', hint: 'Nominalize: "consumption of energy" or "energy consumption".', technique: 'nominalization' },
    { text: 'When the factory closed, many workers lost their jobs.', hint: 'Use "The closure of the factory" to restructure the sentence.', technique: 'clause_restructure' },
    { text: 'The data was not reliable.', hint: 'Add the prefix "un-" to "reliable".', technique: 'word_form' },
    { text: 'The treatment did not alleviate the patient\'s pain.', hint: 'Replace "did not alleviate" with an antonym verb.', technique: 'antonym_negation' },
    { text: 'Urban areas tend to have higher levels of pollution than rural areas.', hint: 'Replace urban, tend to have, levels, pollution, rural.', technique: 'synonym' },
    { text: 'The manager reviewed the report thoroughly.', hint: 'Try: The report was thoroughly reviewed by...', technique: 'active_passive' },
    { text: 'Temperatures are rising due to greenhouse gas emissions.', hint: 'Nominalize: "a rise in temperatures" or "the rise of temperatures".', technique: 'nominalization' },
    { text: 'Although the research was expensive, it produced valuable results.', hint: 'Use "In spite of" + noun phrase (nominalization of the clause).', technique: 'clause_restructure' },
    { text: 'The proposal was not feasible given the limited budget.', hint: 'Use the prefix "un-" on "feasible".', technique: 'word_form' },
    { text: 'The plan did not succeed.', hint: 'Replace "did not succeed" with its antonym.', technique: 'antonym_negation' },
    { text: 'Governments should invest more in renewable energy sources.', hint: 'Replace: governments, invest, renewable energy, sources.', technique: 'synonym' },
    { text: 'The council approved the new development plan.', hint: 'Convert to passive voice.', technique: 'active_passive' },
    { text: 'Children develop language skills through reading.', hint: 'Nominalize: "the development of language skills".', technique: 'nominalization' },
    { text: 'Once the vaccine was approved, hospitals began large-scale distribution.', hint: 'Use "Following the approval of the vaccine" to restructure.', technique: 'clause_restructure' },
    { text: 'The results were not consistent with previous findings.', hint: 'Replace "not consistent with" with an antonym verb.', technique: 'antonym_negation' },
    { text: 'Access to clean drinking water remains a major challenge for developing nations.', hint: 'Replace all key words with synonyms.', technique: 'synonym' },
    { text: 'Archaeologists uncovered the ancient ruins last year.', hint: 'Convert: The ancient ruins were...', technique: 'active_passive' },
    { text: 'Sea levels are rising because ice caps are melting.', hint: 'Nominalize both processes: "the rise of sea levels" and "the melting of ice caps".', technique: 'nominalization' },
    { text: 'The more a person reads, the better their vocabulary becomes.', hint: 'Restructure: Extensive reading leads to...', technique: 'clause_restructure' },
    { text: 'The response was not adequate.', hint: 'Use "in-" prefix to make a single-word antonym.', technique: 'word_form' },
    { text: 'The government did not address the root causes of poverty.', hint: 'Replace "did not address" with an antonym phrase.', technique: 'antonym_negation' },
    { text: 'The rapid advancement of technology has transformed modern communication.', hint: 'Replace: rapid, advancement, technology, transformed, modern, communication.', technique: 'synonym' },
    { text: 'Doctors performed the operation successfully.', hint: 'Passive: The operation was...', technique: 'active_passive' },
    { text: 'The birth rate declined because women entered the workforce.', hint: 'Nominalize: "the entry of women into the workforce".', technique: 'nominalization' },
    { text: 'Unless immediate action is taken, the crisis will worsen.', hint: 'Restructure: "Without immediate action, ..." or "Failure to act immediately will..."', technique: 'clause_restructure' },
    { text: 'The theory was not proven by the experiment.', hint: 'Replace with an antonym: the experiment... the theory.', technique: 'antonym_negation' },
    { text: 'Many people in developing countries lack access to quality healthcare.', hint: 'Replace: Many people, developing countries, lack, quality healthcare.', technique: 'synonym' },
    { text: 'Engineers designed the new bridge to withstand earthquakes.', hint: 'Passive: The new bridge was designed...', technique: 'active_passive' },
    { text: 'The economy grew because exports increased significantly.', hint: 'Nominalize: "economic growth" resulted from "a significant increase in exports".', technique: 'nominalization' },
    { text: 'While some countries have reduced carbon emissions, others have increased them.', hint: 'Use "Whereas" and restructure the contrast.', technique: 'clause_restructure' },
    { text: 'The situation was not improving despite intervention.', hint: 'Replace "not improving" with its antonym verb.', technique: 'antonym_negation' },
    { text: 'The widespread use of social media has changed how people communicate.', hint: 'Replace: widespread use, social media, changed, communicate.', technique: 'synonym' },
    { text: 'The university published the research findings last month.', hint: 'Passive: The research findings were...', technique: 'active_passive' },
    { text: 'More people are migrating from rural areas to cities.', hint: 'Nominalize: "an increase in rural-to-urban migration".', technique: 'nominalization' },
    { text: 'Not only does pollution harm human health, but it also damages ecosystems.', hint: 'Restructure using "Both...and" or drop the inversion.', technique: 'clause_restructure' },
    { text: 'The drug was not safe for children under five.', hint: 'Use "un-" prefix on "safe".', technique: 'word_form' },
    { text: 'The student did not pass the final examination.', hint: 'Use the antonym of "pass" directly.', technique: 'antonym_negation' },
    { text: 'Regular physical activity reduces the risk of obesity and type 2 diabetes.', hint: 'Replace: regular, physical activity, reduces, risk, obesity.', technique: 'synonym' },
    { text: 'The committee presented the recommendations to the board.', hint: 'Passive: The recommendations were presented...', technique: 'active_passive' },
    { text: 'Interest rates rose because inflation increased.', hint: 'Nominalize: "a rise in interest rates" resulted from "an increase in inflation".', technique: 'nominalization' },
    { text: 'The longer a species is isolated, the more distinct it becomes.', hint: 'Restructure: "Prolonged isolation of a species leads to..."', technique: 'clause_restructure' },
    { text: 'The argument was not convincing.', hint: 'Use "un-" prefix on "convincing".', technique: 'word_form' },
    { text: 'The organisation did not fulfil its objectives.', hint: 'Replace "did not fulfil" with the antonym verb meaning to fail in achieving.', technique: 'antonym_negation' },
    { text: 'Advances in medical technology have significantly extended human life expectancy.', hint: 'Replace: advances, medical technology, significantly, extended, life expectancy.', technique: 'synonym' },
    { text: 'Scientists identified three new species in the rainforest.', hint: 'Passive: Three new species were identified...', technique: 'active_passive' },
    { text: 'Children learn best when they are taught in their first language.', hint: 'Nominalize: "children\'s learning is most effective when instruction..."', technique: 'nominalization' },
    { text: 'So severe was the drought that crops failed across the region.', hint: 'Restructure the inverted sentence to standard word order.', technique: 'clause_restructure' },
    { text: 'The contract was not valid.', hint: 'Use "in-" prefix: "invalid".', technique: 'word_form' },
    { text: 'The government did not prioritise environmental protection.', hint: 'Replace "did not prioritise" — what does the opposite mean?', technique: 'antonym_negation' },
    { text: 'The quality of education varies significantly between wealthy and poor communities.', hint: 'Replace: quality, varies, significantly, wealthy, communities.', technique: 'synonym' },
    { text: 'The author wrote the novel in just six months.', hint: 'Passive: The novel was written...', technique: 'active_passive' },
    { text: 'The demand for clean energy is increasing worldwide.', hint: 'Nominalize: "an increase in the demand for clean energy".', technique: 'nominalization' },
    { text: 'It was the introduction of antibiotics that revolutionised modern medicine.', hint: 'Remove the cleft structure: "The introduction of antibiotics revolutionised..."', technique: 'clause_restructure' },
    { text: 'The method was not accurate.', hint: 'Use "in-" prefix: "inaccurate".', technique: 'word_form' },
    { text: 'The reforms did not reduce inequality.', hint: 'Replace "did not reduce inequality" — what is the antonym process?', technique: 'antonym_negation' },
    { text: 'Biodiversity loss is one of the most pressing environmental concerns of our time.', hint: 'Replace: biodiversity loss, pressing, environmental concerns.', technique: 'synonym' },
    { text: 'Researchers are studying the long-term effects of screen time on children.', hint: 'Passive with nominalization: "The long-term effects of screen time...are being studied..."', technique: 'active_passive' },
    { text: 'Forests absorb large amounts of carbon dioxide from the atmosphere.', hint: 'Nominalize: "the absorption of carbon dioxide by forests".', technique: 'nominalization' },
    { text: 'The faster cities build cycling infrastructure, the more people will cycle.', hint: 'Restructure the comparative correlation: "Rapid investment in cycling infrastructure..."', technique: 'clause_restructure' },
    { text: 'The evidence was not clear.', hint: 'Use "un-" prefix: "unclear".', technique: 'word_form' },
    { text: 'The hospital did not meet hygiene standards.', hint: 'Replace "did not meet" with an appropriate antonym.', technique: 'antonym_negation' },
    { text: 'Climate change poses an existential threat to low-lying island nations.', hint: 'Replace: climate change, poses, existential threat, low-lying, island nations.', technique: 'synonym' },
    { text: 'The prime minister announced new economic reforms yesterday.', hint: 'Passive: New economic reforms were announced...', technique: 'active_passive' },
    { text: 'Deforestation accelerated because timber prices rose.', hint: 'Nominalize: "the acceleration of deforestation resulted from..."', technique: 'nominalization' },
    { text: 'The more diverse a team is, the more creative its output tends to be.', hint: 'Restructure: "Team diversity tends to produce more creative outcomes."', technique: 'clause_restructure' },
    { text: 'The reading was not legible.', hint: 'Use "il-" prefix: "illegible".', technique: 'word_form' },
    { text: 'The medication did not cure the infection.', hint: 'Replace "did not cure" with an antonym meaning it worsened or failed to heal.', technique: 'antonym_negation' },
    { text: 'The number of people living in extreme poverty has declined over the past two decades.', hint: 'Replace: number of people, extreme poverty, declined, past two decades.', technique: 'synonym' },
    { text: 'The committee reviewed all submitted applications.', hint: 'Passive: All submitted applications were reviewed...', technique: 'active_passive' },
    { text: 'Urbanisation accelerated because industrial jobs attracted rural migrants.', hint: 'Nominalize: "the acceleration of urbanisation was driven by..."', technique: 'nominalization' },
    { text: 'Were governments to invest more in education, social mobility would increase.', hint: 'Restructure the inverted conditional: "If governments were to invest..."', technique: 'clause_restructure' },
    { text: 'The system was not reliable.', hint: 'Use "un-" prefix: "unreliable".', technique: 'word_form' },
    { text: 'The initiative did not gain public support.', hint: 'Replace "did not gain support" with what this implies — people rejected or opposed it.', technique: 'antonym_negation' },
    { text: 'The destruction of natural habitats threatens the survival of many animal species.', hint: 'Replace: destruction, natural habitats, threatens, survival, animal species.', technique: 'synonym' },
    { text: 'The architect designed the building to maximise natural light.', hint: 'Passive: The building was designed...', technique: 'active_passive' },
    { text: 'The divorce rate rose because economic pressures increased.', hint: 'Nominalize: "an increase in economic pressures led to..."', technique: 'nominalization' },
    { text: 'Not until the digital age did information become so widely accessible.', hint: 'Restructure the inversion: "Information did not become widely accessible until..."', technique: 'clause_restructure' },
    { text: 'The behaviour was not acceptable.', hint: 'Use "un-" prefix: "unacceptable".', technique: 'word_form' },
    { text: 'The policy did not benefit low-income families.', hint: 'Replace "did not benefit" with its antonym — what did it do to them instead?', technique: 'antonym_negation' },
    { text: 'Young people today face greater financial pressures than previous generations.', hint: 'Replace: young people, face, financial pressures, previous generations.', technique: 'synonym' },
    { text: 'Researchers published their findings in a peer-reviewed journal.', hint: 'Passive: The findings were published...', technique: 'active_passive' },
    { text: 'The supply of affordable housing decreased because construction costs rose.', hint: 'Nominalize: "a decrease in affordable housing supply resulted from..."', technique: 'nominalization' },
    { text: 'As a country\'s GDP grows, its demand for energy increases.', hint: 'Restructure: "Economic growth in a country drives an increase in energy demand."', technique: 'clause_restructure' },
    { text: 'The evidence was not sufficient to draw conclusions.', hint: 'Use "in-" prefix: "insufficient".', technique: 'word_form' },
    { text: 'The intervention did not prevent the conflict.', hint: 'Replace "did not prevent" — what does the opposite action mean?', technique: 'antonym_negation' },
    { text: 'The rise of automation has led to significant changes in the labour market.', hint: 'Replace: rise of automation, led to, significant, changes, labour market.', technique: 'synonym' },
    { text: 'The engineer tested the prototype under extreme conditions.', hint: 'Passive: The prototype was tested...', technique: 'active_passive' },
    { text: 'Migration from rural to urban areas increased because cities offered better opportunities.', hint: 'Nominalize: "rural-to-urban migration increased due to..."', technique: 'nominalization' },
    { text: 'The problem is not poverty itself but the inequality that accompanies it.', hint: 'Restructure: "Rather than poverty per se, it is inequality that..."', technique: 'clause_restructure' },
    { text: 'The approach was not practical.', hint: 'Use "im-" prefix: "impractical".', technique: 'word_form' },
    { text: 'The new regulations did not improve working conditions.', hint: 'Replace "did not improve" with an antonym.', technique: 'antonym_negation' },
    { text: 'The global population is projected to reach ten billion by 2050.', hint: 'Replace: global population, projected, reach, ten billion, 2050.', technique: 'synonym' },
    { text: 'The government allocated significant resources to the healthcare sector.', hint: 'Passive: Significant resources were allocated...', technique: 'active_passive' },
    { text: 'Tourism increased because the government promoted the region.', hint: 'Nominalize: "an increase in tourism resulted from..."', technique: 'nominalization' },
    { text: 'Only by addressing the root causes can governments achieve lasting change.', hint: 'Restructure: "Lasting change requires governments to address the root causes."', technique: 'clause_restructure' },
    { text: 'The proposal was not transparent.', hint: 'What single adjective is the antonym of transparent? Use it directly.', technique: 'antonym_negation' },
    { text: 'Economic globalisation has intensified competition among businesses worldwide.', hint: 'Replace: economic globalisation, intensified, competition, businesses, worldwide.', technique: 'synonym' },
    { text: 'The teacher explained the concept clearly to the students.', hint: 'Passive: The concept was clearly explained...', technique: 'active_passive' },
    { text: 'Violence increases when poverty rises.', hint: 'Nominalize: "an increase in poverty leads to an increase in violence".', technique: 'nominalization' },
    { text: 'Although the experiment was flawed, it yielded useful data.', hint: 'Use "Despite the experiment\'s flaws..."', technique: 'clause_restructure' },
    { text: 'The regulation was not relevant to small businesses.', hint: 'Use "ir-" prefix: "irrelevant".', technique: 'word_form' },
    { text: 'The company did not comply with environmental regulations.', hint: 'Replace "did not comply with" — what is the antonym action?', technique: 'antonym_negation' },
    { text: 'The growing awareness of mental health has reduced stigma in many communities.', hint: 'Replace: growing awareness, mental health, reduced, stigma, communities.', technique: 'synonym' },
    { text: 'The board rejected the proposal unanimously.', hint: 'Passive: The proposal was rejected...', technique: 'active_passive' },
    { text: 'Demand for housing rose because the population grew rapidly.', hint: 'Nominalize: "rapid population growth resulted in..."', technique: 'nominalization' },
    { text: 'Scarcely had the announcement been made when protests began.', hint: 'Restructure the inversion: "Almost immediately after the announcement..."', technique: 'clause_restructure' },
    { text: 'The decision was not rational.', hint: 'Use "ir-" prefix: "irrational".', technique: 'word_form' },
    { text: 'The project did not meet its deadlines.', hint: 'Replace "did not meet" with the antonym of "meeting deadlines".', technique: 'antonym_negation' },
    { text: 'The increasing number of electric vehicles on the road is reducing air pollution.', hint: 'Replace: increasing number, electric vehicles, reducing, air pollution.', technique: 'synonym' },
    { text: 'The professor delivered an inspiring lecture on climate science.', hint: 'Passive: An inspiring lecture was delivered...', technique: 'active_passive' },
    { text: 'Carbon emissions rose because countries burned more fossil fuels.', hint: 'Nominalize: "an increase in fossil fuel consumption led to..."', technique: 'nominalization' },
    { text: 'The greater the investment in early education, the stronger the long-term economic returns.', hint: 'Restructure: "Higher early education investment produces stronger long-term economic returns."', technique: 'clause_restructure' },
    { text: 'The diagnosis was not accurate.', hint: 'Use "in-" prefix: "inaccurate".', technique: 'word_form' },
    { text: 'The new software did not solve the existing problems.', hint: 'Replace "did not solve" with the antonym.', technique: 'antonym_negation' },
    { text: 'Access to quality education is a fundamental human right.', hint: 'Replace: access to, quality education, fundamental, human right.', technique: 'synonym' },
    { text: 'The researchers collected samples from multiple locations.', hint: 'Passive: Samples were collected...', technique: 'active_passive' },
    { text: 'Inequality widened because wages stagnated while living costs rose.', hint: 'Nominalize: "stagnant wages and rising living costs contributed to..."', technique: 'nominalization' },
    { text: 'Such was the scale of the disaster that international aid was mobilised immediately.', hint: 'Restructure from inverted form: "The disaster was so large that..."', technique: 'clause_restructure' },
    { text: 'The policy was not consistent.', hint: 'Use "in-" prefix: "inconsistent".', technique: 'word_form' },
    { text: 'The study did not confirm the relationship between diet and longevity.', hint: 'Replace "did not confirm" with an antonym verb.', technique: 'antonym_negation' },
    { text: 'Scientists warn that coral reefs could disappear within decades if ocean temperatures continue to rise.', hint: 'Replace: scientists, warn, coral reefs, disappear, ocean temperatures.', technique: 'synonym' },
    { text: 'The judge delivered the verdict after three days of deliberation.', hint: 'Passive: The verdict was delivered...', technique: 'active_passive' },
    { text: 'Food insecurity rose because droughts reduced crop yields.', hint: 'Nominalize: "reduced crop yields due to drought led to..."', technique: 'nominalization' },
    { text: 'It was the industrial revolution that first created large-scale environmental damage.', hint: 'Remove the cleft and restructure as a plain sentence.', technique: 'clause_restructure' },
    { text: 'The evidence was not impartial.', hint: 'What single adjective is the antonym of "impartial"?', technique: 'antonym_negation' },
    { text: 'The digital transformation of the economy has created new industries and eliminated old ones.', hint: 'Replace: digital transformation, economy, created, eliminated.', technique: 'synonym' },
    { text: 'The government passed new legislation to combat financial fraud.', hint: 'Passive: New legislation was passed...', technique: 'active_passive' },
    { text: 'Trust in public institutions declined because corruption scandals emerged.', hint: 'Nominalize: "the emergence of corruption scandals led to..."', technique: 'nominalization' },
    { text: 'Had the company acted sooner, the financial losses could have been avoided.', hint: 'Restructure from inverted conditional: "If the company had acted sooner..."', technique: 'clause_restructure' },
    { text: 'The logic was not valid.', hint: 'Use "in-" prefix: "invalid".', technique: 'word_form' },
    { text: 'The new approach did not address the underlying causes of the problem.', hint: 'Replace "did not address" — what action is the antonym?', technique: 'antonym_negation' },
    { text: 'The expansion of online learning has made education more accessible to people worldwide.', hint: 'Replace: expansion, online learning, accessible, people worldwide.', technique: 'synonym' },
    { text: 'The court upheld the original decision.', hint: 'Passive: The original decision was upheld...', technique: 'active_passive' },
    { text: 'Productivity fell because workers were poorly trained.', hint: 'Nominalize: "a lack of adequate worker training led to..."', technique: 'nominalization' },
    { text: 'The more technologically advanced a society becomes, the more energy it consumes.', hint: 'Restructure: "Technological advancement in a society is accompanied by increased energy consumption."', technique: 'clause_restructure' },
    { text: 'The forecast was not reliable.', hint: 'Use "un-" prefix: "unreliable".', technique: 'word_form' },
    { text: 'The company did not disclose all relevant financial information.', hint: 'Replace "did not disclose" — what is the antonym action?', technique: 'antonym_negation' },
    { text: 'Water scarcity is becoming an increasingly critical issue in arid regions.', hint: 'Replace: water scarcity, increasingly critical, issue, arid regions.', technique: 'synonym' },
    { text: 'The committee examined the evidence thoroughly.', hint: 'Passive: The evidence was thoroughly examined...', technique: 'active_passive' },
    { text: 'Innovation slowed because research funding was cut.', hint: 'Nominalize: "cuts to research funding led to..."', technique: 'nominalization' },
    { text: 'Rarely has science advanced as rapidly as it has in the past century.', hint: 'Restructure the inversion: "Science has seldom advanced as rapidly as it has..."', technique: 'clause_restructure' },
    { text: 'The material was not transparent.', hint: 'What single adjective means the opposite of transparent?', technique: 'antonym_negation' },
    { text: 'The rise of populism has challenged the stability of democratic institutions globally.', hint: 'Replace: rise of populism, challenged, stability, democratic institutions, globally.', technique: 'synonym' },
    { text: 'The panel reviewed all submitted designs.', hint: 'Passive: All submitted designs were reviewed...', technique: 'active_passive' },
    { text: 'Species diversity fell because habitats were destroyed.', hint: 'Nominalize: "habitat destruction led to..."', technique: 'nominalization' },
    { text: 'Although many challenges remain, significant progress has been made.', hint: 'Use "Despite the many challenges that remain, significant progress..."', technique: 'clause_restructure' },
    { text: 'The instructions were not clear.', hint: 'Use "un-" prefix: "unclear".', technique: 'word_form' },
    { text: 'The investment did not yield the expected returns.', hint: 'Replace "did not yield" — what verb means the investment produced less than expected?', technique: 'antonym_negation' },
    { text: 'Technological innovation is transforming the nature of work across all industries.', hint: 'Replace: technological innovation, transforming, nature of work, industries.', technique: 'synonym' },
    { text: 'The government funded research into renewable energy technologies.', hint: 'Passive: Research into renewable energy technologies was funded...', technique: 'active_passive' },
    { text: 'Health outcomes improved because governments invested in sanitation.', hint: 'Nominalize: "government investment in sanitation led to..."', technique: 'nominalization' },
    { text: 'Only when all nations cooperate can global problems be resolved.', hint: 'Restructure from inversion: "Global problems can only be resolved when all nations cooperate."', technique: 'clause_restructure' },
    { text: 'The policy was not fair.', hint: 'Use "un-" prefix: "unfair".', technique: 'word_form' },
    { text: 'The decision did not take into account the needs of minority groups.', hint: 'Replace "did not take into account" with an antonym.', technique: 'antonym_negation' },
    { text: 'The widespread availability of processed food has contributed to rising obesity rates.', hint: 'Replace: widespread availability, processed food, contributed to, rising obesity rates.', technique: 'synonym' },
    { text: 'The survey collected data from over one thousand participants.', hint: 'Passive: Data was collected from over one thousand participants...', technique: 'active_passive' },
    { text: 'Carbon levels rose because countries relied more heavily on coal.', hint: 'Nominalize: "increased reliance on coal contributed to..."', technique: 'nominalization' },
    { text: 'The longer governments delay climate action, the greater the cost of intervention.', hint: 'Restructure: "Delayed climate action increases the cost of intervention."', technique: 'clause_restructure' },
    { text: 'The decision was not justified.', hint: 'Use "un-" prefix: "unjustified".', technique: 'word_form' },
    { text: 'The welfare system did not support the most vulnerable members of society.', hint: 'Replace "did not support" with an antonym phrase.', technique: 'antonym_negation' },
    { text: 'The global demand for clean energy is rising as countries seek to reduce carbon emissions.', hint: 'Replace: global demand, clean energy, rising, countries, reduce, carbon emissions.', technique: 'synonym' },
    { text: 'The hospital introduced stricter hygiene protocols.', hint: 'Passive: Stricter hygiene protocols were introduced...', technique: 'active_passive' },
    { text: 'Unemployment increased because the manufacturing sector declined.', hint: 'Nominalize: "the decline of the manufacturing sector led to..."', technique: 'nominalization' },
    { text: 'Not until the 20th century did women gain full voting rights in most countries.', hint: 'Restructure from inversion: "Women did not gain full voting rights in most countries until the 20th century."', technique: 'clause_restructure' },
    { text: 'The process was not transparent.', hint: 'What does "lacked ___" mean here? Fill in the noun form of transparent.', technique: 'antonym_negation' },
    { text: 'Advances in genetic engineering offer significant potential for treating inherited diseases.', hint: 'Replace: advances, genetic engineering, significant potential, treating, inherited diseases.', technique: 'synonym' },
    { text: 'The court ordered the company to pay compensation.', hint: 'Passive: The company was ordered to pay compensation...', technique: 'active_passive' },
    { text: 'Youth unemployment rose because schools failed to provide relevant skills training.', hint: 'Nominalize: "the failure of schools to provide relevant skills training contributed to..."', technique: 'nominalization' },
    { text: 'Were scientists to discover a cure for Alzheimer\'s, it would transform eldercare globally.', hint: 'Restructure from inverted conditional: "If scientists were to discover..."', technique: 'clause_restructure' },
    { text: 'The test was not valid.', hint: 'Use "in-" prefix: "invalid".', technique: 'word_form' },
    { text: 'The new drug did not improve patient outcomes.', hint: 'Replace "did not improve" — what did the drug do to outcomes instead?', technique: 'antonym_negation' },
    { text: 'The erosion of press freedom undermines democracy and the public\'s right to information.', hint: 'Replace: erosion of press freedom, undermines, democracy, right to information.', technique: 'synonym' },
    { text: 'The scientist published three papers last year.', hint: 'Passive: Three papers were published by the scientist...', technique: 'active_passive' },
    { text: 'Economic inequality widened because tax cuts benefited the wealthy.', hint: 'Nominalize: "tax cuts that benefited the wealthy led to..."', technique: 'nominalization' },
    { text: 'What matters most in education is not memorisation but critical thinking.', hint: 'Restructure: "Critical thinking, rather than memorisation, is the most important aspect of education."', technique: 'clause_restructure' },
    { text: 'The water was not potable.', hint: 'What single word means "not safe to drink"? Use the prefix "im-".', technique: 'word_form' },
    { text: 'The charity did not reach its fundraising target.', hint: 'Replace "did not reach" — what word means it came short of its goal?', technique: 'antonym_negation' },
    { text: 'The introduction of microplastics into the food chain poses serious risks to human health.', hint: 'Replace: introduction, microplastics, food chain, poses, risks, human health.', technique: 'synonym' },
    { text: 'The team leader assigned tasks to each member.', hint: 'Passive: Tasks were assigned to each member...', technique: 'active_passive' },
    { text: 'Public trust declined because institutions failed to maintain transparency.', hint: 'Nominalize: "the failure of institutions to maintain transparency led to..."', technique: 'nominalization' },
    { text: 'The more educated a population is, the higher its standard of living tends to be.', hint: 'Restructure: "Higher levels of education in a population are associated with a higher standard of living."', technique: 'clause_restructure' },
    { text: 'The medication was not appropriate for elderly patients.', hint: 'Use "in-" prefix: "inappropriate".', technique: 'word_form' },
    { text: 'The policy did not achieve its stated objectives.', hint: 'Replace "did not achieve" — the policy fell... of its objectives.', technique: 'antonym_negation' },
    { text: 'Global temperatures have risen by approximately 1.2 degrees Celsius since the industrial revolution.', hint: 'Replace: global temperatures, risen, approximately, industrial revolution.', technique: 'synonym' },
    { text: 'The manager evaluated all candidates fairly.', hint: 'Passive: All candidates were evaluated fairly...', technique: 'active_passive' },
    { text: 'Stress levels rose because working hours increased.', hint: 'Nominalize: "an increase in working hours led to higher stress levels".', technique: 'nominalization' },
    { text: 'Such has been the pace of change that many traditional industries have disappeared.', hint: 'Restructure from inverted form: "The pace of change has been so rapid that..."', technique: 'clause_restructure' },
    { text: 'The child was not capable of understanding the concept.', hint: 'Use "in-" prefix on "capable": "incapable".', technique: 'word_form' },
    { text: 'The government did not listen to the scientific evidence on climate change.', hint: 'Replace "did not listen to" — what action is the antonym in context?', technique: 'antonym_negation' },
    { text: 'The prevalence of mental health disorders among young adults is increasing.', hint: 'Replace: prevalence, mental health disorders, young adults, increasing.', technique: 'synonym' },
    { text: 'The council passed the planning application after a lengthy review.', hint: 'Passive: The planning application was passed...', technique: 'active_passive' },
    { text: 'Life expectancy improved because nutrition and sanitation improved.', hint: 'Nominalize: "improvements in nutrition and sanitation led to..."', technique: 'nominalization' },
    { text: 'Only by reducing consumption can we lower our environmental footprint.', hint: 'Restructure from inversion: "Reducing consumption is the only way we can lower our environmental footprint."', technique: 'clause_restructure' },
    { text: 'The results were not reproducible.', hint: 'Use "ir-" prefix: "irreproducible".', technique: 'word_form' },
    { text: 'The programme did not achieve its goals.', hint: 'Replace "did not achieve its goals" — it fell... of its goals.', technique: 'antonym_negation' },
    { text: 'The social media landscape is changing rapidly, with new platforms emerging every year.', hint: 'Replace: social media landscape, rapidly, platforms, emerging.', technique: 'synonym' },
    { text: 'The engineers developed a new algorithm to improve search results.', hint: 'Passive: A new algorithm was developed...', technique: 'active_passive' },
    { text: 'Child poverty increased because welfare benefits were reduced.', hint: 'Nominalize: "reductions in welfare benefits contributed to..."', technique: 'nominalization' },
    { text: 'The problem is not the technology itself but how it is used.', hint: 'Restructure: "Rather than the technology itself, it is the way it is used that is the problem."', technique: 'clause_restructure' },
    { text: 'The environment was not safe for workers.', hint: 'Use "un-" prefix: "unsafe".', technique: 'word_form' },
    { text: 'The regime did not respect human rights.', hint: 'Replace "did not respect" with the antonym — what did the regime do to human rights?', technique: 'antonym_negation' },
    { text: 'Ocean acidification threatens the survival of marine ecosystems globally.', hint: 'Replace: ocean acidification, threatens, survival, marine ecosystems.', technique: 'synonym' },
    { text: 'The company released a detailed environmental report.', hint: 'Passive: A detailed environmental report was released...', technique: 'active_passive' },
    { text: 'Social mobility fell because educational opportunities became less equal.', hint: 'Nominalize: "declining equality of educational opportunity led to..."', technique: 'nominalization' },
    { text: 'Barely had the negotiations ended when fighting resumed.', hint: 'Restructure from inversion: "Almost immediately after negotiations ended, fighting resumed."', technique: 'clause_restructure' },
    { text: 'The behaviour was not professional.', hint: 'Use "un-" prefix: "unprofessional".', technique: 'word_form' },
    { text: 'The authorities did not act to prevent the crisis.', hint: 'Replace "did not act to prevent" — the authorities... to prevent the crisis.', technique: 'antonym_negation' },
    { text: 'The interconnectedness of global financial markets means that economic shocks can spread rapidly.', hint: 'Replace: interconnectedness, global financial markets, economic shocks, spread rapidly.', technique: 'synonym' },
    { text: 'The government implemented tax reforms to boost economic growth.', hint: 'Passive: Tax reforms were implemented...', technique: 'active_passive' },
    { text: 'Educational attainment improved because school funding increased.', hint: 'Nominalize: "an increase in school funding led to improvements in..."', technique: 'nominalization' },
    { text: 'It is only through cooperation that nations can address global challenges effectively.', hint: 'Restructure from cleft: "Addressing global challenges effectively requires cooperation between nations."', technique: 'clause_restructure' },
    { text: 'The calculation was not correct.', hint: 'Use "in-" prefix: "incorrect".', technique: 'word_form' },
    { text: 'The new law did not reduce crime rates.', hint: 'Replace "did not reduce" — what happened to crime rates as a result?', technique: 'antonym_negation' },
    { text: 'The shift towards renewable energy sources is essential for achieving carbon neutrality.', hint: 'Replace: shift towards, renewable energy, essential, achieving, carbon neutrality.', technique: 'synonym' },
    { text: 'The school launched a new literacy programme.', hint: 'Passive: A new literacy programme was launched...', technique: 'active_passive' },
    { text: 'Crime increased because poverty intensified.', hint: 'Nominalize: "an intensification of poverty contributed to..."', technique: 'nominalization' },
    { text: 'No sooner had peace been established than conflict reignited.', hint: 'Restructure from inversion: "Almost immediately after peace was established, conflict reignited."', technique: 'clause_restructure' },
    { text: 'The investment was not profitable.', hint: 'Use "un-" prefix: "unprofitable".', technique: 'word_form' },
    { text: 'The treatment did not produce the desired results.', hint: 'Replace "did not produce the desired results" — the treatment fell... of expectations.', technique: 'antonym_negation' },
    { text: 'The growing frequency of extreme weather events is linked to rising global temperatures.', hint: 'Replace: growing frequency, extreme weather events, linked to, global temperatures.', technique: 'synonym' },
    { text: 'The health authority issued new vaccination guidelines.', hint: 'Passive: New vaccination guidelines were issued...', technique: 'active_passive' },
    { text: 'Trust in journalism declined because misinformation spread online.', hint: 'Nominalize: "the spread of online misinformation led to..."', technique: 'nominalization' },
    { text: 'The extent to which plastic pollution harms marine life cannot be overstated.', hint: 'Restructure: "Plastic pollution causes very serious harm to marine life."', technique: 'clause_restructure' },
    { text: 'The analysis was not thorough.', hint: 'What single adjective means "not thorough"? (The opposite is "comprehensive")', technique: 'antonym_negation' },
    { text: 'Food security remains a critical issue in sub-Saharan Africa.', hint: 'Replace: food security, remains, critical issue, sub-Saharan Africa.', technique: 'synonym' },
    { text: 'The firm invested heavily in digital infrastructure.', hint: 'Passive: Heavy investment was made by the firm...', technique: 'active_passive' },
    { text: 'Pollution increased because industries expanded without regulation.', hint: 'Nominalize: "the unregulated expansion of industries contributed to..."', technique: 'nominalization' },
    { text: 'The moment the vaccine was distributed, infection rates began to fall.', hint: 'Restructure: "Upon the distribution of the vaccine, infection rates began to fall."', technique: 'clause_restructure' },
    { text: 'The regulation was not enforceable.', hint: 'Use "un-" prefix: "unenforceable".', technique: 'word_form' },
    { text: 'The economic model did not account for environmental costs.', hint: 'Replace "did not account for" — what did the model do to environmental costs?', technique: 'antonym_negation' },
    { text: 'The increasing use of electric vehicles is reducing urban air pollution.', hint: 'Replace: increasing use, electric vehicles, reducing, urban air pollution.', technique: 'synonym' },
    { text: 'The research team collected over five hundred data points.', hint: 'Passive: Over five hundred data points were collected...', technique: 'active_passive' },
    { text: 'Air quality improved because factories reduced their emissions.', hint: 'Nominalize: "a reduction in factory emissions led to..."', technique: 'nominalization' },
    { text: 'Were it not for medical advances, many diseases would still be incurable.', hint: 'Restructure: "Without medical advances, many diseases would still be incurable."', technique: 'clause_restructure' },
    { text: 'The device was not compatible with older operating systems.', hint: 'Use "in-" prefix: "incompatible".', technique: 'word_form' },
    { text: 'The charity did not allocate funds effectively.', hint: 'Replace "did not allocate funds effectively" — it... funds.', technique: 'antonym_negation' },
    { text: 'The digital divide continues to limit access to technology for marginalised communities.', hint: 'Replace: digital divide, continues, limit, access, technology, marginalised communities.', technique: 'synonym' },
    { text: 'The panel discussed all major issues during the conference.', hint: 'Passive: All major issues were discussed during the conference...', technique: 'active_passive' },
    { text: 'Reading scores fell because schools cut literacy funding.', hint: 'Nominalize: "cuts to literacy funding in schools led to..."', technique: 'nominalization' },
    { text: 'So great is the need for affordable housing that it has become a political crisis.', hint: 'Restructure from inversion: "The need for affordable housing is so great that..."', technique: 'clause_restructure' },
    { text: 'The model was not accurate.', hint: 'Use "in-" prefix: "inaccurate".', technique: 'word_form' },
    { text: 'The programme did not reduce dropout rates.', hint: 'Replace "did not reduce" — what happened to dropout rates?', technique: 'antonym_negation' },
    { text: 'The integration of artificial intelligence into healthcare is transforming patient diagnosis.', hint: 'Replace: integration, artificial intelligence, healthcare, transforming, patient diagnosis.', technique: 'synonym' },
    { text: 'The government awarded the contract to a local firm.', hint: 'Passive: The contract was awarded to a local firm...', technique: 'active_passive' },
    { text: 'Social trust fell because corruption became widespread.', hint: 'Nominalize: "the spread of corruption led to..."', technique: 'nominalization' },
    { text: 'The more languages a person speaks, the greater their cognitive flexibility.', hint: 'Restructure: "Speaking multiple languages is associated with greater cognitive flexibility."', technique: 'clause_restructure' },
    { text: 'The outcome was not predictable.', hint: 'Use "un-" prefix: "unpredictable".', technique: 'word_form' },
    { text: 'The factory did not reduce its carbon footprint.', hint: 'Replace "did not reduce" — what did the factory do to its carbon footprint?', technique: 'antonym_negation' },
    { text: 'The overuse of antibiotics has led to the emergence of drug-resistant bacteria.', hint: 'Replace: overuse, antibiotics, led to, emergence, drug-resistant bacteria.', technique: 'synonym' },
    { text: 'The local authority constructed a new community centre.', hint: 'Passive: A new community centre was constructed...', technique: 'active_passive' },
    { text: 'Food prices rose because drought reduced agricultural output.', hint: 'Nominalize: "drought-related reductions in agricultural output contributed to..."', technique: 'nominalization' },
    { text: 'Unless new conservation strategies are adopted, many species face extinction.', hint: 'Restructure: "Without new conservation strategies, many species face extinction."', technique: 'clause_restructure' },
    { text: 'The translation was not accurate.', hint: 'Use "in-" prefix: "inaccurate".', technique: 'word_form' },
    { text: 'The environmental policy did not achieve the desired reduction in emissions.', hint: 'Replace "did not achieve the desired reduction" — it fell... of the target.', technique: 'antonym_negation' },
    { text: 'The proliferation of single-use plastics is a significant contributor to marine pollution.', hint: 'Replace: proliferation, single-use plastics, significant contributor, marine pollution.', technique: 'synonym' },
    { text: 'The team tested the new drug on a sample group.', hint: 'Passive: The new drug was tested on a sample group...', technique: 'active_passive' },
    { text: 'Student performance declined because funding was cut.', hint: 'Nominalize: "cuts to funding led to a decline in student performance".', technique: 'nominalization' },
    { text: 'Rarely does a single policy change have such wide-ranging social consequences.', hint: 'Restructure from inversion: "It is rare for a single policy change to have such wide-ranging social consequences."', technique: 'clause_restructure' },
    { text: 'The decision was not well-considered.', hint: 'Use "ill-" prefix: "ill-considered".', technique: 'word_form' },
    { text: 'The authorities did not respond to the warnings.', hint: 'Replace "did not respond to" — what did the authorities do with the warnings?', technique: 'antonym_negation' },
    { text: 'The growing gap between rich and poor is one of the defining challenges of the 21st century.', hint: 'Replace: growing gap, rich and poor, defining challenges, 21st century.', technique: 'synonym' },
    { text: 'Scientists detected increased levels of methane in the atmosphere.', hint: 'Passive: Increased levels of methane were detected in the atmosphere...', technique: 'active_passive' },
    { text: 'The gender pay gap widened because women were concentrated in lower-paid sectors.', hint: 'Nominalize: "the concentration of women in lower-paid sectors contributed to..."', technique: 'nominalization' },
    { text: 'Though the initiative was underfunded, it still produced measurable results.', hint: 'Use "Despite the underfunding of the initiative..." to restructure.', technique: 'clause_restructure' },
    { text: 'The result was not what we expected.', hint: 'Replace "not what we expected" with a single adjective meaning surprising or unforeseeable.', technique: 'antonym_negation' },
    { text: 'The rise of automation is fundamentally reshaping labour markets worldwide.', hint: 'Replace: rise of automation, fundamentally reshaping, labour markets, worldwide.', technique: 'synonym' },
    { text: 'The research team published their findings in a reputable journal.', hint: 'Passive: The findings were published in a reputable journal...', technique: 'active_passive' },
    { text: 'Disease spread because people lacked clean water.', hint: 'Nominalize: "the absence of clean water contributed to the spread of disease".', technique: 'nominalization' },
    { text: 'It is the unequal distribution of wealth that perpetuates cycles of poverty.', hint: 'Remove the cleft: "The unequal distribution of wealth perpetuates cycles of poverty."', technique: 'clause_restructure' },
    { text: 'The outcome was not anticipated.', hint: 'Use "un-" prefix: "unanticipated".', technique: 'word_form' },
    { text: 'The economic system did not distribute wealth equitably.', hint: 'Replace "did not distribute wealth equitably" — what did it do to wealth distribution?', technique: 'antonym_negation' },
    { text: 'Deforestation at current rates will lead to the collapse of many tropical ecosystems.', hint: 'Replace: deforestation, current rates, collapse, tropical ecosystems.', technique: 'synonym' },
    { text: 'The developer built fifty affordable homes last year.', hint: 'Passive: Fifty affordable homes were built last year...', technique: 'active_passive' },
    { text: 'Voter turnout declined because people lost faith in institutions.', hint: 'Nominalize: "a loss of public faith in institutions contributed to declining voter turnout".', technique: 'nominalization' },
    { text: 'The faster electric vehicles are adopted, the sooner emissions targets can be met.', hint: 'Restructure: "Faster adoption of electric vehicles would accelerate the achievement of emissions targets."', technique: 'clause_restructure' },
    { text: 'The assumption was not valid.', hint: 'Use "in-" prefix: "invalid".', technique: 'word_form' },
    { text: 'The corporate sector did not take adequate responsibility for environmental damage.', hint: 'Replace "did not take responsibility" — what is the antonym action?', technique: 'antonym_negation' },
    { text: 'The combination of rising temperatures and declining rainfall is threatening food security in many regions.', hint: 'Replace: combination, rising temperatures, declining rainfall, threatening, food security, regions.', technique: 'synonym' },
    { text: 'The university awarded scholarships to twenty students.', hint: 'Passive: Scholarships were awarded to twenty students...', technique: 'active_passive' },
    { text: 'Inequality persisted because systemic barriers prevented social mobility.', hint: 'Nominalize: "systemic barriers to social mobility perpetuated inequality".', technique: 'nominalization' },
    { text: 'So acute is the shortage of affordable housing that many families are homeless.', hint: 'Restructure: "The shortage of affordable housing is so acute that many families are homeless."', technique: 'clause_restructure' },
    { text: 'The relationship was not clear.', hint: 'Use "un-" prefix: "unclear".', technique: 'word_form' },
    { text: 'The authorities did not enforce the law consistently.', hint: 'Replace "did not enforce" — what did the authorities do with law enforcement?', technique: 'antonym_negation' },
    { text: 'The loss of biodiversity represents an irreversible threat to the planet\'s ecological balance.', hint: 'Replace: loss of biodiversity, represents, irreversible threat, ecological balance.', technique: 'synonym' },
    { text: 'The judge sentenced the accused to five years in prison.', hint: 'Passive: The accused was sentenced to five years...', technique: 'active_passive' },
    { text: 'Social cohesion declined because income inequality widened.', hint: 'Nominalize: "widening income inequality led to a decline in social cohesion".', technique: 'nominalization' },
    { text: 'Had adequate warning systems been in place, the disaster could have been mitigated.', hint: 'Restructure: "If adequate warning systems had been in place, the disaster could have been mitigated."', technique: 'clause_restructure' },
    { text: 'The network was not secure.', hint: 'Use "in-" prefix: "insecure".', technique: 'word_form' },
    { text: 'The housing policy did not consider the needs of low-income groups.', hint: 'Replace "did not consider" — it... the needs of low-income groups.', technique: 'antonym_negation' },
    { text: 'Technological progress has made previously impossible tasks routine and accessible.', hint: 'Replace: technological progress, previously impossible, routine, accessible.', technique: 'synonym' },
    { text: 'The committee approved the budget unanimously.', hint: 'Passive: The budget was unanimously approved...', technique: 'active_passive' },
    { text: 'Literacy rates fell because school attendance declined.', hint: 'Nominalize: "declining school attendance led to a fall in literacy rates".', technique: 'nominalization' },
    { text: 'What is most striking about modern cities is not their size but their inequality.', hint: 'Restructure: "Inequality, rather than size, is the most striking feature of modern cities."', technique: 'clause_restructure' },
    { text: 'The source was not credible.', hint: 'Use "in-" prefix: "incredible/incredible" or the better option — what single word means "lacking credibility"?', technique: 'antonym_negation' },
    { text: 'The widespread adoption of smartphones has changed how people consume news.', hint: 'Replace: widespread adoption, smartphones, changed, consume news.', technique: 'synonym' },
    { text: 'The laboratory confirmed the test results.', hint: 'Passive: The test results were confirmed by the laboratory...', technique: 'active_passive' },
    { text: 'Educational inequality grew because school funding was distributed unevenly.', hint: 'Nominalize: "uneven distribution of school funding contributed to growing educational inequality".', technique: 'nominalization' },
    { text: 'The greater the corruption in a country, the weaker its institutions become.', hint: 'Restructure: "Corruption weakens institutions proportionally as it increases."', technique: 'clause_restructure' },
    { text: 'The chemical was not soluble in water.', hint: 'Use "in-" prefix: "insoluble".', technique: 'word_form' },
    { text: 'The reform did not address gender inequality in the workplace.', hint: 'Replace "did not address" — the reform... gender inequality.', technique: 'antonym_negation' },
    { text: 'The rapid development of artificial intelligence raises important ethical questions.', hint: 'Replace: rapid development, artificial intelligence, raises, ethical questions.', technique: 'synonym' },
    { text: 'The police arrested three suspects following the investigation.', hint: 'Passive: Three suspects were arrested following the investigation...', technique: 'active_passive' },
    { text: 'Consumer spending fell because unemployment rose.', hint: 'Nominalize: "rising unemployment led to a fall in consumer spending".', technique: 'nominalization' },
    { text: 'No matter how difficult the circumstances, scientists must maintain objectivity.', hint: 'Restructure: "Regardless of the difficulty of circumstances, scientists must maintain objectivity."', technique: 'clause_restructure' },
    { text: 'The answer was not complete.', hint: 'Use "in-" prefix: "incomplete".', technique: 'word_form' },
    { text: 'The campaign did not raise public awareness effectively.', hint: 'Replace "did not raise awareness effectively" — the campaign... to raise public awareness.', technique: 'antonym_negation' },
    { text: 'The loss of coastal wetlands reduces natural flood protection for nearby communities.', hint: 'Replace: loss, coastal wetlands, reduces, natural flood protection, communities.', technique: 'synonym' },
    { text: 'The organisation trained hundreds of volunteers.', hint: 'Passive: Hundreds of volunteers were trained...', technique: 'active_passive' },
    { text: 'Forest cover declined because logging companies were unregulated.', hint: 'Nominalize: "unregulated logging contributed to a decline in forest cover".', technique: 'nominalization' },
    { text: 'It was not until the 1960s that environmental protection became a political priority.', hint: 'Restructure from not-until cleft: "Environmental protection only became a political priority in the 1960s."', technique: 'clause_restructure' },
    { text: 'The policy was not coherent.', hint: 'Use "in-" prefix: "incoherent".', technique: 'word_form' },
    { text: 'The company did not meet safety standards.', hint: 'Replace "did not meet" — the company... safety standards.', technique: 'antonym_negation' },
    { text: 'Space exploration has yielded numerous scientific advances that benefit life on Earth.', hint: 'Replace: space exploration, yielded, numerous, scientific advances, benefit, life on Earth.', technique: 'synonym' },
    { text: 'The researchers analysed five years of climate data.', hint: 'Passive: Five years of climate data were analysed...', technique: 'active_passive' },
    { text: 'Violent crime fell because community policing expanded.', hint: 'Nominalize: "the expansion of community policing contributed to a fall in violent crime".', technique: 'nominalization' },
    { text: 'Seldom has such comprehensive legislation been passed in such a short time.', hint: 'Restructure from inversion: "It is rare for such comprehensive legislation to be passed in such a short time."', technique: 'clause_restructure' },
    { text: 'The findings were not conclusive.', hint: 'Use "in-" prefix: "inconclusive".', technique: 'word_form' },
    { text: 'The administration did not respond to early warnings about the outbreak.', hint: 'Replace "did not respond to" — what did the administration do with the warnings?', technique: 'antonym_negation' },
    { text: 'The impact of social media on political discourse is difficult to measure but undeniable.', hint: 'Replace: impact, social media, political discourse, difficult to measure, undeniable.', technique: 'synonym' },
    { text: 'The government reduced spending on public services.', hint: 'Passive: Spending on public services was reduced...', technique: 'active_passive' },
    { text: 'Levels of air pollution fell because new emission standards were introduced.', hint: 'Nominalize: "the introduction of new emission standards led to a fall in air pollution".', technique: 'nominalization' },
    { text: 'However challenging the task, researchers must continue their work.', hint: 'Restructure: "Regardless of how challenging the task is, researchers must continue their work."', technique: 'clause_restructure' },
    { text: 'The approach was not systematic.', hint: 'Use "un-" prefix: "unsystematic".', technique: 'word_form' },
    { text: 'The government did not prioritise public health in its budget.', hint: 'Replace "did not prioritise" — it... public health.', technique: 'antonym_negation' },
    { text: 'The transition to a circular economy could reduce waste and conserve natural resources.', hint: 'Replace: transition, circular economy, reduce waste, conserve, natural resources.', technique: 'synonym' },
    { text: 'The engineers constructed a new water treatment facility.', hint: 'Passive: A new water treatment facility was constructed...', technique: 'active_passive' },
    { text: 'Social trust declined because civic institutions were weakened.', hint: 'Nominalize: "the weakening of civic institutions led to a decline in social trust".', technique: 'nominalization' },
    { text: 'The issue is not simply one of supply, but of distribution.', hint: 'Restructure: "Rather than supply alone, distribution is the core issue."', technique: 'clause_restructure' },
    { text: 'The infrastructure was not adequate.', hint: 'Use "in-" prefix: "inadequate".', technique: 'word_form' },
    { text: 'The investment did not generate the expected returns.', hint: 'Replace "did not generate expected returns" — the investment... expectations.', technique: 'antonym_negation' },
    { text: 'The link between early childhood education and long-term social outcomes is well-documented.', hint: 'Replace: link, early childhood education, long-term social outcomes, well-documented.', technique: 'synonym' },
    { text: 'The architect designed the school to maximise natural ventilation.', hint: 'Passive: The school was designed to maximise natural ventilation...', technique: 'active_passive' },
    { text: 'Air quality improved because car use decreased.', hint: 'Nominalize: "a decrease in car use led to improvements in air quality".', technique: 'nominalization' },
    { text: 'Only through sustained investment in skills training can economies remain competitive.', hint: 'Restructure from inversion: "Sustained investment in skills training is necessary for economies to remain competitive."', technique: 'clause_restructure' },
    { text: 'The correlation was not significant.', hint: 'Use "in-" prefix: "insignificant".', technique: 'word_form' },
    { text: 'The institution did not uphold the principles of academic freedom.', hint: 'Replace "did not uphold" — it... the principles of academic freedom.', technique: 'antonym_negation' },
    { text: 'The increasing frequency of extreme weather events is closely linked to climate change.', hint: 'Replace: increasing frequency, extreme weather events, closely linked, climate change.', technique: 'synonym' },
    { text: 'Volunteers planted one thousand trees in the national park.', hint: 'Passive: One thousand trees were planted in the national park...', technique: 'active_passive' },
    { text: 'Greenhouse gas emissions fell because industries switched to cleaner energy.', hint: 'Nominalize: "the switch to cleaner energy by industries led to a fall in greenhouse gas emissions".', technique: 'nominalization' },
    { text: 'The moment climate targets are missed, further warming becomes locked in.', hint: 'Restructure: "Once climate targets are missed, further warming becomes locked in."', technique: 'clause_restructure' },
    { text: 'The regulation was not proportionate.', hint: 'Use "dis-" prefix: "disproportionate".', technique: 'word_form' },
    { text: 'The charity did not communicate its impact effectively.', hint: 'Replace "did not communicate effectively" — it... to communicate its impact.', technique: 'antonym_negation' },
    { text: 'The democratisation of information through the internet has transformed public discourse.', hint: 'Replace: democratisation, information, internet, transformed, public discourse.', technique: 'synonym' },
    { text: 'The laboratory processed all samples within forty-eight hours.', hint: 'Passive: All samples were processed within forty-eight hours...', technique: 'active_passive' },
    { text: 'Biodiversity declined because forests were cleared for agriculture.', hint: 'Nominalize: "the clearance of forests for agriculture led to a decline in biodiversity".', technique: 'nominalization' },
    { text: 'Provided that adequate resources are allocated, the project will succeed.', hint: 'Restructure: "The project\'s success depends on the allocation of adequate resources."', technique: 'clause_restructure' },
    { text: 'The solution was not sustainable.', hint: 'Use "un-" prefix: "unsustainable".', technique: 'word_form' },
    { text: 'The party did not honour its election pledges.', hint: 'Replace "did not honour" — the party... its election pledges.', technique: 'antonym_negation' },
    { text: 'The impact of rising sea levels on coastal infrastructure will be enormous.', hint: 'Replace: impact, rising sea levels, coastal infrastructure, enormous.', technique: 'synonym' },
    { text: 'The panel evaluated the evidence before making its recommendation.', hint: 'Passive: The evidence was evaluated by the panel before...', technique: 'active_passive' },
    { text: 'Urban poverty grew because job losses outpaced job creation.', hint: 'Nominalize: "a net loss of jobs contributed to an increase in urban poverty".', technique: 'nominalization' },
    { text: 'Never before has the need for international cooperation been so great.', hint: 'Restructure: "The need for international cooperation is greater now than it has ever been."', technique: 'clause_restructure' },
    { text: 'The approach was not evidence-based.', hint: 'Use "non-" prefix: "non-evidence-based" or rephrase as "lacked evidence".', technique: 'word_form' },
    { text: 'The company did not take responsibility for the environmental damage.', hint: 'Replace "did not take responsibility" — the company... responsibility.', technique: 'antonym_negation' },
    { text: 'The global shift towards sustainable agriculture is gaining momentum.', hint: 'Replace: global shift, sustainable agriculture, gaining momentum.', technique: 'synonym' },
    { text: 'The hospital implemented new infection control measures.', hint: 'Passive: New infection control measures were implemented...', technique: 'active_passive' },
    { text: 'Civic engagement fell because distrust in government grew.', hint: 'Nominalize: "growing distrust in government led to a fall in civic engagement".', technique: 'nominalization' },
    { text: 'The longer a conflict continues, the harder it becomes to achieve peace.', hint: 'Restructure: "Prolonged conflict makes it increasingly difficult to achieve peace."', technique: 'clause_restructure' },
    { text: 'The policy was not enforceable.', hint: 'Use "un-" prefix: "unenforceable".', technique: 'word_form' },
    { text: 'The media did not report the story accurately.', hint: 'Replace "did not report accurately" — the media... the story.', technique: 'antonym_negation' },
    { text: 'The relationship between poverty and educational underachievement is well-established.', hint: 'Replace: relationship, poverty, educational underachievement, well-established.', technique: 'synonym' },
    { text: 'The planning department approved the construction proposal.', hint: 'Passive: The construction proposal was approved...', technique: 'active_passive' },
    { text: 'Carbon emissions fell because fuel efficiency standards improved.', hint: 'Nominalize: "improvements in fuel efficiency standards led to a fall in carbon emissions".', technique: 'nominalization' },
    { text: 'So compelling was the evidence that the court reversed its decision.', hint: 'Restructure: "The evidence was so compelling that the court reversed its decision."', technique: 'clause_restructure' },
    { text: 'The strategy was not coherent.', hint: 'Use "in-" prefix: "incoherent".', technique: 'word_form' },
    { text: 'The authority did not act on the complaints it received.', hint: 'Replace "did not act on" — the authority... the complaints.', technique: 'antonym_negation' },
];
