---
deployment:
  tasks:
    - export DEPLOYPATH=/home/learncar/iltes.learncarebd.com
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && npm install --production=false
    - cd $DEPLOYPATH && npm run build
